FROM node:22-alpine AS build

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_PUBLISHABLE_KEY
ARG VITE_DOCUMENT_INTELLIGENCE_MODE=baseline
ARG VITE_DOCUMENT_INTELLIGENCE_TIMEOUT_MS=240000
ARG VITE_PARSER_IA_LOCAL=false
ARG VITE_PARSER_IA_MODE=disabled
ARG VITE_PRISMA_GIT_COMMIT=unknown

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_PUBLISHABLE_KEY=$VITE_SUPABASE_PUBLISHABLE_KEY
ENV VITE_DOCUMENT_INTELLIGENCE_MODE=$VITE_DOCUMENT_INTELLIGENCE_MODE
ENV VITE_DOCUMENT_INTELLIGENCE_TIMEOUT_MS=$VITE_DOCUMENT_INTELLIGENCE_TIMEOUT_MS
ENV VITE_PARSER_IA_LOCAL=$VITE_PARSER_IA_LOCAL
ENV VITE_PARSER_IA_MODE=$VITE_PARSER_IA_MODE
ENV VITE_PRISMA_GIT_COMMIT=$VITE_PRISMA_GIT_COMMIT

RUN pnpm run build:web

FROM nginx:1.27-alpine

COPY --from=build /app/web/dist /usr/share/nginx/html
COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
