-- Reuses the fully synthetic M73 fixture inside the runner's rollback transaction.
reset role;
create function public.m74_curate(p_action text default 'alias',p_concept uuid default public.m73_id('negotiation'),p_scope public.knowledge_scope default 'organization') returns jsonb
language sql security invoker as $$select public.curate_profile_competency(public.m73_id('a'),public.m73_id('person'),public.m73_id('current'),3,'Termo desconhecido','Termo desconhecido',p_scope,p_action,p_concept,'Equivalência conferida na fonte','Conceito proposto','skill')$$;
grant execute on function public.m74_curate(text,uuid,public.knowledge_scope) to authenticated,anon;
savepoint global_curation;
update public.platform_users set access_profile='super_admin',group_id=null where auth_user_id=m73_id('owner');
set local role authenticated;
select set_config('request.jwt.claim.sub',m73_id('owner')::text,true);
select m73_assert(public.m74_curate('alias',m73_id('negotiation'),'global')->>'outcome'='alias','super admin can explicitly curate Global');
reset role;
select m73_assert(exists(select 1 from knowledge_terms where term='Termo desconhecido' and term_type='alias' and scope='global'),'explicit Global scope persisted');
rollback to savepoint global_curation;
release savepoint global_curation;
savepoint admin_curation;
update public.platform_users set access_profile='admin' where auth_user_id=m73_id('owner');
insert into public.organization_memberships(organization_id,user_id,role) values(m73_id('a'),m73_id('owner'),'admin') on conflict(organization_id,user_id) do update set role='admin';
set local role authenticated;
select set_config('request.jwt.claim.sub',m73_id('owner')::text,true);
select m73_assert(public.m74_curate()->>'outcome'='alias','organization admin can curate company alias');
reset role;
rollback to savepoint admin_curation;
release savepoint admin_curation;
savepoint human_conflict;
update public.knowledge_inbox set observation_ids=array[(select id from public.knowledge_observations where original_term='Excel e Word' limit 1)] where original_term='Termo desconhecido';
set local role authenticated;
select set_config('request.jwt.claim.sub',m73_id('owner')::text,true);
select m73_reject('select public.m74_curate()','23505');
reset role;
rollback to savepoint human_conflict;
release savepoint human_conflict;
set local role anon;
select m73_reject('select public.m74_curate()','42501');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub',m73_id('member')::text,true);
select m73_reject('select public.m74_curate()','42501');
select m73_assert(public.load_person_professional_evidence_map_v3(m73_id('a'),m73_id('person'))#>>'{normalization,declaredCount}'='4','member retains authorized read only');
select set_config('request.jwt.claim.sub',m73_id('outsider')::text,true);
select m73_reject('select public.m74_curate()','42501');
select m73_reject(format('select public.load_person_professional_evidence_map_v3(%L,%L)',m73_id('a'),m73_id('person')),'42501');
select set_config('request.jwt.claim.sub',m73_id('inactive')::text,true);
select m73_reject('select public.m74_curate()','42501');
select set_config('request.jwt.claim.sub',m73_id('owner')::text,true);
select m73_reject(format('select public.m74_curate(%L,%L,%L)','alias',m73_id('negotiation'),'global'),'42501');
select m73_reject(format('select public.m74_curate(%L,%L)','alias',m73_id('word-b')),'42501');
select m73_reject(format('select public.m74_curate(%L,%L)','alias',m73_id('pmo')),'42501');
select m73_reject(format('select public.curate_profile_competency(%L,%L,%L,3,%L,%L,%L,%L,%L,%L,%L,%L)',m73_id('a'),m73_id('person'),m73_id('old'),'Termo desconhecido','Termo desconhecido','organization','alias',m73_id('negotiation'),'Motivo válido','','skill'),'40001');
select m73_reject(format('select public.curate_profile_competency(%L,%L,%L,3,%L,%L,%L,%L,%L,%L,%L,%L)',m73_id('a'),m73_id('person'),m73_id('current'),'Texto forjado','Termo desconhecido','organization','alias',m73_id('negotiation'),'Motivo válido','','skill'),'40001');
select m73_reject(format('select public.curate_profile_competency(%L,%L,%L,3,%L,%L,%L,%L,%L,%L,%L,%L)',m73_id('a'),m73_id('person'),m73_id('current'),'Termo desconhecido','Termo desconhecido','organization','alias',m73_id('negotiation'),'x','','skill'),'22023');
do $$declare result jsonb;begin
  result:=public.m74_curate('proposal',null);
  perform public.m73_assert(result->>'outcome'='proposal','proposal saved without automatic publication');
  perform public.m73_assert(exists(select 1 from jsonb_array_elements(result#>'{projection,normalization,items}') i where i->>'normalizedTerm'='Termo desconhecido' and i->>'state'='unresolved'),'proposal retains pending declaration');
end$$;
select m73_reject('select public.m74_curate(''proposal'',null)','23505');
do $$declare result jsonb; projection jsonb;begin
  result:=public.m74_curate();
  projection:=result->'projection';
  perform public.m73_assert(result->>'outcome'='alias','alias committed with returned projection');
  perform public.m73_assert(exists(select 1 from jsonb_array_elements(projection#>'{normalization,items}') i where i->>'normalizedTerm'='Termo desconhecido' and i->>'state'='resolved'),'curated item immediately resolved without model or queue');
  perform public.m73_assert(exists(select 1 from jsonb_array_elements(projection->'associations') a where a#>>'{evidence,title}'='Termo desconhecido' and a#>>'{explanation,methodVersion}'='profile-competency-curation-1.0.0' and a#>>'{explanation,humanDecision}' like '%Equivalência%'),'human provenance and reason visible');
  perform public.m73_assert((select count(*)=1 from jsonb_array_elements(projection->'associations') a where a->>'observedTerm'='Excel e Word'),'previous compound human decision preserved');
  perform public.m73_assert(not exists(select 1 from jsonb_array_elements(projection->'associations') a where a->>'nature'<>'declared'),'curation never produces demonstrated evidence');
end$$;
select m73_reject('select public.m74_curate()','40001');
reset role;
select m73_assert((select profile_data='{"competencies":["Excel e Word","PMO","negociação","Termo desconhecido"]}'::jsonb from professional_profiles where id=m73_id('current')),'curation preserves reviewed profile');
select m73_assert((select profile_data='{"competencies":["Legado"]}'::jsonb from professional_profiles where id=m73_id('old')),'curation preserves historical snapshot');
select m73_assert((select count(*)=1 from knowledge_terms where term='Termo desconhecido' and term_type='alias' and status='approved'),'one audited approved alias');
select m73_assert((select sum(request_count)=1 from profile_competency_normalization_runs),'curation does not call AI or create another run');
select m73_assert(not exists(select 1 from knowledge_concepts where canonical_label='Conceito proposto'),'proposal did not create approved concept');
