-- Synthetic fixture in a mandatory rollback; no real human decisions.
insert into public.person_private_data(organization_id,person_id,birth_date) values(m83_id('a'),m83_id('person'),'1994-01-01');
insert into public.vacancies(id,organization_id,job_role_id,title,status,current_version_id) values(m83_id('vacancy2'),m83_id('a'),m83_id('role'),'Outra posição','open',null);
insert into public.vacancy_versions(id,organization_id,vacancy_id,version,title,source_kind) values(m83_id('v3'),m83_id('a'),m83_id('vacancy2'),1,'Outra posição','manual');
update public.vacancies set current_version_id=m83_id('v3') where id=m83_id('vacancy2');
insert into public.match_evaluations(id,organization_id,person_id,vacancy_id,vacancy_version_id,evaluation_data,matching_version,prompt_version,model_version) values(m83_id('saved-score'),m83_id('a'),m83_id('person'),m83_id('vacancy'),m83_id('v2'),jsonb_build_object('stableMatch',jsonb_build_object('score',jsonb_build_object('score',78,'profileVersion',m83_id('profile'),'positionVersion',m83_id('v2')))),'synthetic','synthetic','synthetic');
insert into public.matching_score_states(organization_id,person_id,vacancy_id,evaluation_id) values(m83_id('a'),m83_id('person'),m83_id('vacancy'),m83_id('saved-score'));
create temp table follow_up_baseline as select jsonb_build_object('vacancies',(select jsonb_agg(to_jsonb(v) order by id) from public.vacancies v),'profiles',(select jsonb_agg(to_jsonb(p) order by id) from public.professional_profiles p),'scores',(select coalesce(jsonb_agg(to_jsonb(e) order by id),'[]') from public.match_evaluations e)) value;
grant select on follow_up_baseline to authenticated;
create temp table follow_up_result(value jsonb);grant all on follow_up_result to authenticated;
set local role authenticated;
select set_config('request.jwt.claim.sub',m83_id('member')::text,true);
select m83_reject(format('select public.get_position_follow_up(%L,%L)',m83_id('a'),m83_id('vacancy')),'42501');
select m83_reject(format('select public.mutate_position_follow_up(%L,%L,''add'',%L)',m83_id('a'),m83_id('vacancy'),m83_id('person')),'42501');
select set_config('request.jwt.claim.sub',m83_id('outsider')::text,true);
select m83_reject(format('select public.get_position_follow_up(%L,%L)',m83_id('a'),m83_id('vacancy')),'42501');
select set_config('request.jwt.claim.sub',m83_id('inactive')::text,true);
select m83_reject(format('select public.get_position_follow_up(%L,%L)',m83_id('a'),m83_id('vacancy')),'42501');
select set_config('request.jwt.claim.sub','',true);
select m83_reject(format('select public.get_position_follow_up(%L,%L)',m83_id('a'),m83_id('vacancy')),'42501');
select set_config('request.jwt.claim.sub',m83_id('recruiter')::text,true);
select m83_assert(public.get_position_follow_up(m83_id('a'),m83_id('vacancy'))->'process'='null','opening a position never creates a process');
select m83_reject('select * from public.position_evaluation_entries','42501');
select m83_reject('delete from public.position_evaluation_history','42501');
insert into follow_up_result select public.mutate_position_follow_up(m83_id('a'),m83_id('vacancy'),'add',m83_id('person'),null,jsonb_build_object('profileId',m83_id('profile'),'positionId',m83_id('v2')));
select m83_assert((select value#>>'{entries,0,stage}'='awaiting_evaluation' and value#>>'{entries,0,score}'='78' and value#>>'{entries,0,age}' is not null from follow_up_result),'explicit entry, persisted score, authorized derived age');
select m83_assert(not(public.get_position_follow_up(m83_id('a'),m83_id('vacancy'))::text like '%1994-01-01%'),'birth date not exposed');
select m83_assert(jsonb_array_length(public.mutate_position_follow_up(m83_id('a'),m83_id('vacancy'),'add',m83_id('person'),null,jsonb_build_object('profileId',m83_id('profile'),'positionId',m83_id('v2')))->'entries')=1,'duplicate inclusion idempotent');
select m83_assert(jsonb_array_length(public.get_position_follow_up(m83_id('a'),m83_id('vacancy'))->'history')=1,'idempotence preserves audit');
select m83_reject(format('select public.mutate_position_follow_up(%L,%L,''add'',%L,null,%L)',m83_id('a'),m83_id('vacancy'),m83_id('person'),jsonb_build_object('profileId',m83_id('old'),'positionId',m83_id('v2'))),'40001');
select m83_reject(format('select public.get_position_follow_up(%L,%L)',m83_id('b'),m83_id('vacancy')),'42501');
select m83_reject(format('select public.mutate_position_follow_up(%L,%L,''add'',%L)',m83_id('a'),m83_id('vacancy'),m83_id('other-person')),'22023');
select m83_reject(format('select public.mutate_position_follow_up(%L,%L,''stage'',%L,0,''{"stage":"evaluating"}'')',m83_id('a'),m83_id('vacancy'),m83_id('person')),'40001');
select m83_reject(format('select public.mutate_position_follow_up(%L,%L,''stage'',%L,1,''{"stage":"decision_recorded"}'')',m83_id('a'),m83_id('vacancy'),m83_id('person')),'22023');
select m83_reject(format('select public.mutate_position_follow_up(%L,%L,''stage'',%L,1,''{"stage":"evaluating","score":99}'')',m83_id('a'),m83_id('vacancy'),m83_id('person')),'22023');
select m83_assert(public.mutate_position_follow_up(m83_id('a'),m83_id('vacancy'),'stage',m83_id('person'),1,'{"stage":"awaiting_interview"}')#>>'{entries,0,details,interview}' is null,'drag to interview does not schedule');
select m83_reject(format('select public.mutate_position_follow_up(%L,%L,''details'',%L,2,%L)',m83_id('a'),m83_id('vacancy'),m83_id('person'),jsonb_build_object('assignee',m83_id('member'))),'22023');
select m83_reject(format('select public.mutate_position_follow_up(%L,%L,''details'',%L,2,''{"notes":{}}'')',m83_id('a'),m83_id('vacancy'),m83_id('person')),'22023');
select m83_reject(format('select public.mutate_position_follow_up(%L,%L,''schedule'',%L,2,''{}'')',m83_id('a'),m83_id('vacancy'),m83_id('person')),'22023');
select m83_reject(format('select public.mutate_position_follow_up(%L,%L,''schedule'',%L,2,''{"at":"2026-10-15T14:00:00-03:00","timezone":"invalid","participants":"Synthetic"}'')',m83_id('a'),m83_id('vacancy'),m83_id('person')),'22023');
select m83_assert(public.mutate_position_follow_up(m83_id('a'),m83_id('vacancy'),'schedule',m83_id('person'),2,'{"at":"2026-10-15T14:00:00-03:00","timezone":"America/Sao_Paulo","participants":"Pessoa sintética e recrutador"}')#>>'{entries,0,stage}'='interview_scheduled','explicit interview schedules');
select m83_assert(public.mutate_position_follow_up(m83_id('a'),m83_id('vacancy'),'schedule',m83_id('person'),3,'{"at":"2026-10-16T14:00:00-03:00","timezone":"America/Sao_Paulo","participants":"Pessoa sintética e recrutador"}')#>>'{entries,0,details,interview,at}' like '2026-10-16%','explicit reschedule audited');
select m83_assert(public.mutate_position_follow_up(m83_id('a'),m83_id('vacancy'),'cancel_interview',m83_id('person'),4)#>>'{entries,0,stage}'='awaiting_interview','cancellation restores awaiting interview');
select m83_assert(public.mutate_position_follow_up(m83_id('a'),m83_id('vacancy'),'stage',m83_id('person'),5,'{"stage":"awaiting_decision"}')#>>'{entries,0,details,decision}' is null,'moving to decision does not decide');
select m83_reject(format('select public.mutate_position_follow_up(%L,%L,''decision'',%L,6,''{"outcome":"proceed","rationale":" "}'')',m83_id('a'),m83_id('vacancy'),m83_id('person')),'22023');
select m83_assert(public.mutate_position_follow_up(m83_id('a'),m83_id('vacancy'),'decision',m83_id('person'),6,'{"outcome":"proceed","rationale":"Decisão humana sintética com evidência consultada"}')#>>'{entries,0,stage}'='decision_recorded','explicit decision with rationale');
select m83_assert(public.mutate_position_follow_up(m83_id('a'),m83_id('vacancy'),'close',m83_id('person'),7)#>>'{entries,0,details,decision,outcome}'='proceed','closing preserves decision');
select m83_reject(format('select public.mutate_position_follow_up(%L,%L,''stage'',%L,8,''{"stage":"evaluating"}'')',m83_id('a'),m83_id('vacancy'),m83_id('person')),'22023');
select m83_assert(public.mutate_position_follow_up(m83_id('a'),m83_id('vacancy'),'reopen',m83_id('person'),8)#>>'{entries,0,stage}'='decision_recorded','explicit reopening preserves phase');
select m83_assert(public.mutate_position_follow_up(m83_id('a'),m83_id('vacancy2'),'add',m83_id('person'),null,jsonb_build_object('profileId',m83_id('profile'),'positionId',m83_id('v3')))#>>'{entries,0,stage}'='awaiting_evaluation','same person independent position');
select m83_assert(public.mutate_position_follow_up(m83_id('a'),m83_id('vacancy2'),'close',m83_id('person'),1)#>>'{entries,0,details,decision}' is null,'closure without conclusion is not rejection');
select m83_assert(jsonb_array_length(public.get_position_follow_up(m83_id('a'),null,m83_id('person'))->'links')=2,'profile links to both processes');
select m83_assert(public.mutate_position_follow_up(m83_id('a'),m83_id('vacancy'),'close_process',null,10)#>>'{entries,0,stage}'='decision_recorded','process close preserves individual stage');
select m83_reject(format('select public.mutate_position_follow_up(%L,%L,''stage'',%L,9,''{"stage":"evaluating"}'')',m83_id('a'),m83_id('vacancy'),m83_id('person')),'22023');
select m83_assert(public.mutate_position_follow_up(m83_id('a'),m83_id('vacancy'),'reopen_process',null,11)#>>'{process,status}'='active','process explicit reopening');
reset role;
select m83_assert((select value from follow_up_baseline)=jsonb_build_object('vacancies',(select jsonb_agg(to_jsonb(v) order by id) from public.vacancies v),'profiles',(select jsonb_agg(to_jsonb(p) order by id) from public.professional_profiles p),'scores',(select coalesce(jsonb_agg(to_jsonb(e) order by id),'[]') from public.match_evaluations e)),'all operational mutations preserve score, profile and position');
select m83_assert((select count(*)=3 from pg_class where oid in ('public.position_evaluation_entries'::regclass,'public.position_evaluation_processes'::regclass,'public.position_evaluation_history'::regclass) and relrowsecurity),'all new tables enforce RLS');
select m83_assert(not has_table_privilege('authenticated','public.position_evaluation_history','INSERT') and not has_table_privilege('service_role','public.position_evaluation_entries','SELECT'),'no direct write or service read grants');
select m83_assert((select count(*)=2 from public.position_evaluation_history where action='add'),'failed operations do not leave partial audit');
select m83_assert(not(public.get_position_follow_up(m83_id('a'),m83_id('vacancy'))::text like '%profileData%'),'board does not expose integral profile data');
set local role anon;
select m83_reject(format('select public.get_position_follow_up(%L,%L)',m83_id('a'),m83_id('vacancy')),'42501');
reset role;
