create temp table pa_state(key text primary key,value jsonb);
grant all on pa_state to authenticated,service_role;
insert into public.vacancy_requirements(id,organization_id,vacancy_id,vacancy_version_id,stable_id,label,importance,category)
values(m83_id('req'),m83_id('a'),m83_id('vacancy'),m83_id('v2'),m83_id('stable'),'JavaScript','required','knowledge');
create temp table pa_preservation as select (select jsonb_agg(to_jsonb(x)) from public.professional_profiles x) profiles,(select jsonb_agg(to_jsonb(x)) from public.match_evaluations x) matching,(select jsonb_agg(to_jsonb(x)) from public.vacancies x) positions;
select m83_assert(private.pa_distribution(20,3)#>'{counts}'='{"easy":6,"medium":8,"hard":6}','distribution exact 20 level3');
select m83_reject('select private.pa_distribution(12,3)','22023');
select m83_reject('select private.pa_distribution(20,6)','22023');
set local role anon;
select m83_reject('select public.position_assessment_workspace(m83_id(''a''),m83_id(''vacancy''),m83_id(''person''))','42501');
select m83_reject('select public.position_assessment_public(''load'',repeat(''a'',64))','42501');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub',m83_id('member')::text,true);
select m83_reject('select public.position_assessment_workspace(m83_id(''a''),m83_id(''vacancy''),m83_id(''person''))','42501');
select set_config('request.jwt.claim.sub',m83_id('recruiter')::text,true);
select m83_reject('select public.position_assessment_workspace(m83_id(''a''),m83_id(''vacancy''),m83_id(''person''))','42501');
select public.mutate_position_follow_up(m83_id('a'),m83_id('vacancy'),'add',m83_id('person'),null,jsonb_build_object('profileId',m83_id('profile'),'positionId',m83_id('v2')));
select m83_reject('insert into public.position_assessments default values','42501');
select m83_reject('select public.position_assessment_public(''load'',repeat(''a'',64))','42501');
insert into pa_state values('workspace',public.position_assessment_workspace(m83_id('a'),m83_id('vacancy'),m83_id('person')));
select m83_assert((select jsonb_array_length(value->'assessments')=0 from pa_state where key='workspace'),'read does not create assessments');
insert into pa_state values('a',public.position_assessment_mutate(m83_id('a'),m83_id('vacancy'),m83_id('person'),'configure',null,null,jsonb_build_object('config',jsonb_build_object('quantity',10,'level',1,'durationMinutes',40,'mode','ai'),'requirementIds',jsonb_build_array(m83_id('req')))));
select m83_reject(format('select public.position_assessment_mutate(%L,%L,%L,''ready'',%L,1)',m83_id('a'),m83_id('vacancy'),m83_id('person'),(select value->>'id' from pa_state where key='a')),'22023');
select m83_reject(format('select public.position_assessment_mutate(%L,%L,%L,''questions'',%L,0,''{"questions":[]}'')',m83_id('a'),m83_id('vacancy'),m83_id('person'),(select value->>'id' from pa_state where key='a')),'40001');
insert into pa_state values('gen',public.position_assessment_generation_request(m83_id('a'),(select (value->>'id')::uuid from pa_state where key='a'),m83_id('gen'),jsonb_build_array(jsonb_build_object('requirementId',m83_id('req'),'difficulty','easy','quantity',6),jsonb_build_object('requirementId',m83_id('req'),'difficulty','medium','quantity',3),jsonb_build_object('requirementId',m83_id('req'),'difficulty','hard','quantity',1))));
select m83_assert(public.position_assessment_generation_request(m83_id('a'),(select (value->>'id')::uuid from pa_state where key='a'),m83_id('gen'),(select value->'distribution' from pa_state where key='gen'))->>'id'=m83_id('gen')::text,'same generation request replays without new reservation');
select m83_reject(format('select public.position_assessment_generation_request(%L,%L,%L,%L)',m83_id('a'),(select value->>'id' from pa_state where key='a'),m83_id('gen-duplicate'),(select value->'distribution' from pa_state where key='gen')),'40001');
reset role;
insert into pa_state select 'questions',jsonb_agg(jsonb_build_object('organizationId',m83_id('a'),'id',m83_id('q'||n),'version','pa-item-1.0.0','requirementId',m83_id('req'),'competencyKey','JavaScript','difficulty',case when n<=6 then 'easy' when n<=9 then 'medium' else 'hard' end,'language','pt-BR','stem','Synthetic question '||n,'options','[{"id":"A","label":"Alpha"},{"id":"B","label":"Beta"},{"id":"C","label":"Gamma"},{"id":"D","label":"Delta"},{"id":"E","label":"Epsilon"}]'::jsonb,'correctOptionId','A','explanation','Synthetic evidence','source','ai','review','pending','provenance',jsonb_build_object('method','synthetic-qa','version','pa-method-1.0.0','authorId',null)) order by n) from generate_series(1,10) n;
set local role service_role;
select public.position_assessment_generation_finish(m83_id('gen'),m83_id('a'),(select value from pa_state where key='questions'),0.01,true);
select m83_reject('select * from public.position_assessment_deliveries','42501');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub',m83_id('recruiter')::text,true);
update pa_state set value=(public.position_assessment_workspace(m83_id('a'),m83_id('vacancy'),m83_id('person'))#>'{assessments,0}') where key='a';
select m83_reject(format('select public.position_assessment_mutate(%L,%L,%L,''ready'',%L,2)',m83_id('a'),m83_id('vacancy'),m83_id('person'),(select value->>'id' from pa_state where key='a')),'22023');
do $$ declare a jsonb; q jsonb; begin select value into a from pa_state where key='a'; for q in select value from jsonb_array_elements(a->'questions') loop a:=public.position_assessment_mutate(m83_id('a'),m83_id('vacancy'),m83_id('person'),'approve',(a->>'id')::uuid,(a->>'revision')::integer,jsonb_build_object('questionId',q->>'id','saveToBank',false)); end loop; update pa_state set value=a where key='a'; end $$;
update pa_state set value=public.position_assessment_mutate(m83_id('a'),m83_id('vacancy'),m83_id('person'),'ready',(value->>'id')::uuid,(value->>'revision')::integer) where key='a';
insert into pa_state values('invite',public.position_assessment_invite(m83_id('a'),(select (value->>'id')::uuid from pa_state where key='a'),m83_id('invite'),'synthetic@example.invalid','Synthetic invitation','Synthetic instructions',now()+interval '7 days'));
select m83_assert((select value->>'state'='queued' from pa_state where key='invite'),'invite is queued, never invented sent');
select m83_assert(not (select value ? 'token' from pa_state where key='invite'),'operator does not receive raw personal token');
select set_config('request.jwt.claim.sub',m83_id('outsider')::text,true);
select m83_reject('select public.position_assessment_workspace(m83_id(''a''),m83_id(''vacancy''),m83_id(''person''))','42501');
reset role;
set local role service_role;
insert into pa_state values('delivery',public.position_assessment_delivery('claim',(select (value->>'deliveryId')::uuid from pa_state where key='invite'),m83_id('a')));
select m83_assert((select (value->>'acquired')::boolean from pa_state where key='delivery'),'backend acquires persisted first attempt and lease');
select m83_assert(not (public.position_assessment_delivery('claim',(select (value->>'deliveryId')::uuid from pa_state where key='invite'),m83_id('a'))->>'acquired')::boolean,'duplicate dispatch does not acquire lease');
insert into pa_state select 'tokenhash',to_jsonb(encode(extensions.digest(value->>'token','sha256'),'hex')) from pa_state where key='delivery';
insert into pa_state values('portal',public.position_assessment_public('load',(select value#>>'{}' from pa_state where key='tokenhash')));
select m83_assert((select jsonb_array_length(value->'questions')=0 from pa_state where key='portal'),'questions absent before explicit start');
update pa_state set value=public.position_assessment_public('start',(select value#>>'{}' from pa_state where key='tokenhash')) where key='portal';
select m83_assert((select jsonb_array_length(value->'questions')=10 and value->>'status'='started' from pa_state where key='portal'),'start exposes exactly five alternatives per question');
select m83_assert((select value::text not like '%correctOptionId%' and value::text not like '%Synthetic evidence%' from pa_state where key='portal'),'portal exposes no answer key or explanation');
select m83_reject(format('select public.position_assessment_public(''save'',%L,''{"revision":1,"answers":{},"marked":["unknown"]}'')',(select value#>>'{}' from pa_state where key='tokenhash')),'22023');
insert into pa_state select 'answers',jsonb_object_agg(q->>'id','A') from pa_state,jsonb_array_elements(value) q where key='questions';
update pa_state set value=public.position_assessment_public('save',(select value#>>'{}' from pa_state where key='tokenhash'),jsonb_build_object('revision',1,'answers',(select value from pa_state where key='answers'),'marked','[]'::jsonb)) where key='portal';
select m83_assert(public.position_assessment_public('save',(select value#>>'{}' from pa_state where key='tokenhash'),jsonb_build_object('revision',1,'answers',(select value from pa_state where key='answers'),'marked','[]'::jsonb))->>'revision'='2','autosave replay idempotent after lost response');
update pa_state set value=public.position_assessment_public('submit',(select value#>>'{}' from pa_state where key='tokenhash'),jsonb_build_object('revision',2,'answers',(select value from pa_state where key='answers'),'marked','[]'::jsonb)) where key='portal';
select m83_assert((select value->>'status'='submitted' and not(value ? 'result') and not(value ? 'questions') from pa_state where key='portal'),'candidate receives completion receipt only');
select m83_assert(public.position_assessment_public('submit',(select value#>>'{}' from pa_state where key='tokenhash'),'{}')->>'status'='submitted','submission replay preserves receipt');
reset role;
select m83_assert((select result->>'correct'='10' from public.position_assessment_attempts),'backend deterministic correction');
select m83_assert((select profiles from pa_preservation)=(select jsonb_agg(to_jsonb(x)) from public.professional_profiles x),'profiles preserved');
select m83_assert((select matching from pa_preservation) is not distinct from (select jsonb_agg(to_jsonb(x)) from public.match_evaluations x),'matching and score preserved');
select m83_assert((select positions from pa_preservation)=(select jsonb_agg(to_jsonb(x)) from public.vacancies x),'position status and definition preserved');
select m83_assert((select count(*)=6 from pg_class where oid in ('public.position_assessments'::regclass,'public.position_assessment_attempts'::regclass,'public.position_assessment_events'::regclass,'public.position_assessment_deliveries'::regclass,'public.position_assessment_generation'::regclass,'public.position_assessment_audit'::regclass) and relrowsecurity),'all assessment tables have RLS');
