select m83_assert((select data from v232_legacy)=(select to_jsonb(a)-'process_id' from public.position_assessments a),'legacy assessment unchanged');
select m83_assert((select bool_and(person_id is null) from public.position_assessment_attempts),'legacy attempts unchanged');
set local role anon;
select m83_reject('select public.process_assessment_workspace(m83_id(''a''),m83_id(''vacancy''))','42501');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub',m83_id('outsider')::text,true);
select m83_reject('select public.process_assessment_workspace(m83_id(''a''),m83_id(''vacancy''))','42501');
select set_config('request.jwt.claim.sub',m83_id('recruiter')::text,true);
select m83_reject('select * from public.position_assessment_batches','42501');
select m83_reject('select public.position_assessment_mutate(m83_id(''a''),m83_id(''vacancy''),m83_id(''person''),''configure'')','22023');
insert into pa_state values('shared',public.position_assessment_mutate(m83_id('a'),m83_id('vacancy'),null,'configure',null,null,jsonb_build_object('config',jsonb_build_object('quantity',10,'level',1,'durationMinutes',60,'mode','ai'),'requirementIds',jsonb_build_array(m83_id('req')))));
select m83_assert((select value->>'person_id' is null and value->>'process_id' is not null and value->>'contract_version'='position-assessment-2.0.0' from pa_state where key='shared'),'new proof belongs to process, never individual');
insert into pa_state values('sharedgen',public.position_assessment_generation_request(m83_id('a'),(select (value->>'id')::uuid from pa_state where key='shared'),m83_id('shared-gen'),(select value->'distribution' from pa_state where key='gen')));
reset role;
set local role service_role;
select public.position_assessment_generation_finish(m83_id('shared-gen'),m83_id('a'),(select value from pa_state where key='questions'),0.01,true);
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub',m83_id('recruiter')::text,true);
update pa_state set value=(public.process_assessment_workspace(m83_id('a'),m83_id('vacancy'))->'assessment') where key='shared';
-- A bad recipient invalidates the entire batch before human approval/outbox writes.
select m83_reject(format('select public.process_assessment_issue(%L,%L,2,%L,%L,''Synthetic invitation'',''Synthetic instructions'',now()+interval ''7 days'')',m83_id('a'),(select value->>'id' from pa_state where key='shared'),m83_id('bad-batch'),jsonb_build_array(jsonb_build_object('personId',m83_id('person'),'email','synthetic@example.invalid'),jsonb_build_object('personId',m83_id('other-person'),'email','invalid'))),'22023');
select m83_assert((public.process_assessment_workspace(m83_id('a'),m83_id('vacancy'))#>>'{assessment,status}')='draft','invalid batch does not approve/freeze');
insert into pa_state values('batch-deadline',to_jsonb(now()+interval '7 days'));
insert into pa_state values('batch',public.process_assessment_issue(m83_id('a'),(select (value->>'id')::uuid from pa_state where key='shared'),2,m83_id('batch'),jsonb_build_array(jsonb_build_object('personId',m83_id('person'),'email','synthetic@example.invalid')),'Synthetic invitation','Synthetic instructions',(select (value#>>'{}')::timestamptz from pa_state where key='batch-deadline')));
select m83_assert((select not(value::text like '%token%') and value#>>'{receipts,0,state}'='queued' from pa_state where key='batch'),'batch queues personal invitations without exposing token');
select m83_assert(public.process_assessment_issue(m83_id('a'),(select (value->>'id')::uuid from pa_state where key='shared'),2,m83_id('batch'),jsonb_build_array(jsonb_build_object('personId',m83_id('person'),'email','synthetic@example.invalid')),'Synthetic invitation','Synthetic instructions',(select (value#>>'{}')::timestamptz from pa_state where key='batch-deadline'))->>'duplicate'='true','lost batch response replays without duplicate invitation');
select m83_reject(format('select public.position_assessment_mutate(%L,%L,null,''configure'',%L,3)',m83_id('a'),m83_id('vacancy'),(select value->>'id' from pa_state where key='shared')),'22023');
select m83_assert((public.position_assessment_workspace(m83_id('a'),m83_id('vacancy'),m83_id('person'))->'attempts') is not null,'legacy individual workspace remains available');
reset role;
select m83_assert((select count(*)=1 from public.position_assessment_attempts where person_id=m83_id('person')),'batch replay creates exactly one application');
select m83_assert((select status='issued' and private.pa_ready(a) from public.position_assessments a where process_id is not null),'one human action approves complete common proof');
create temp table v232_frozen as select questions,config,requirements from public.position_assessments where process_id is not null;
set local role authenticated;
select set_config('request.jwt.claim.sub',m83_id('recruiter')::text,true);
select public.mutate_position_follow_up(m83_id('a'),m83_id('vacancy'),'add',m83_id('late-person'),null,jsonb_build_object('profileId',m83_id('late-profile'),'positionId',m83_id('v2')));
insert into pa_state values('late-batch',public.process_assessment_issue(m83_id('a'),(select (value->>'id')::uuid from pa_state where key='shared'),3,m83_id('late-batch'),jsonb_build_array(jsonb_build_object('personId',m83_id('late-person'),'email','late@example.invalid')),'Synthetic invitation','Synthetic instructions',(select (value#>>'{}')::timestamptz from pa_state where key='batch-deadline')));
select m83_assert(jsonb_array_length(public.position_assessment_workspace(m83_id('a'),m83_id('vacancy'),m83_id('person'))->'attempts')=2,'individual workspace includes legacy and own shared application only');
select m83_assert(jsonb_array_length(public.position_assessment_workspace(m83_id('a'),m83_id('vacancy'),m83_id('late-person'))->'attempts')=1,'individual workspace cannot leak another candidate application');
reset role;
select m83_assert((select questions=(select questions from v232_frozen) and config=(select config from v232_frozen) and requirements=(select requirements from v232_frozen) from public.position_assessments where process_id is not null),'late candidate receives exactly frozen common proof');
select m83_assert((select data from v232_legacy)=(select to_jsonb(a)-'process_id' from public.position_assessments a where process_id is null),'legacy history survives shared send');
set local role service_role;
insert into pa_state values('shared-delivery',public.position_assessment_delivery('claim',(select (value#>>'{receipts,0,deliveryId}')::uuid from pa_state where key='batch'),m83_id('a')));
insert into pa_state values('shared-token',to_jsonb(encode(extensions.digest((select value->>'token' from pa_state where key='shared-delivery'),'sha256'),'hex')));
select m83_assert(public.position_assessment_public('start',(select value#>>'{}' from pa_state where key='shared-token'))->>'contract'='position-assessment-1.0.0','shared proof preserves public portal v1');
select m83_assert(public.position_assessment_public('load',(select value#>>'{}' from pa_state where key='shared-token'))->>'personName' is not null,'shared public portal uses individual application identity');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub',m83_id('recruiter')::text,true);
insert into pa_state values('process-before',public.get_position_follow_up(m83_id('a'),m83_id('vacancy'))->'process');
select public.mutate_position_follow_up_process(m83_id('a'),m83_id('vacancy'),(select (value->>'id')::uuid from pa_state where key='process-before'),'close_process',null,(select (value->>'revision')::integer from pa_state where key='process-before'));
select public.mutate_position_follow_up_process(m83_id('a'),m83_id('vacancy'),(select (value->>'id')::uuid from pa_state where key='process-before'),'reopen_process',null,(select (value->>'revision')::integer+1 from pa_state where key='process-before'));
select m83_assert(public.process_assessment_workspace(m83_id('a'),m83_id('vacancy'))#>>'{assessment,id}'=(select value->>'id' from pa_state where key='shared'),'reopening existing process preserves its exact proof');
update pa_state set value=public.get_position_follow_up(m83_id('a'),m83_id('vacancy'))->'process' where key='process-before';
select public.mutate_position_follow_up_process(m83_id('a'),m83_id('vacancy'),(select (value->>'id')::uuid from pa_state where key='process-before'),'close_process',null,(select (value->>'revision')::integer from pa_state where key='process-before'));
select public.start_position_selection_process(m83_id('a'),m83_id('vacancy'),(select (value->>'id')::uuid from pa_state where key='process-before'),(select (value->>'revision')::integer+1 from pa_state where key='process-before'),m83_id('new-process'));
select m83_assert((public.get_position_follow_up(m83_id('a'),m83_id('vacancy'))#>>'{process,sequence}')='2','new process preserves historical cycle');
select m83_assert(jsonb_array_length(public.get_position_follow_up(m83_id('a'),m83_id('vacancy'))->'entries')=0,'new process does not copy candidates or human decisions');
select m83_reject(format('select public.mutate_position_follow_up_process(%L,%L,%L,''reopen_process'',null,1)',m83_id('a'),m83_id('vacancy'),(select value->>'id' from pa_state where key='process-before')),'40001');
select m83_assert(jsonb_array_length(public.get_position_follow_up_process(m83_id('a'),m83_id('vacancy'),(select (value->>'id')::uuid from pa_state where key='process-before'))->'entries')=2,'historical process remains readable');
select public.process_assessment_reuse(m83_id('a'),m83_id('vacancy'),(public.get_position_follow_up(m83_id('a'),m83_id('vacancy'))#>>'{process,id}')::uuid,(select (value->>'id')::uuid from pa_state where key='shared'));
select m83_assert(jsonb_array_length(public.process_assessment_workspace(m83_id('a'),m83_id('vacancy'))->'attempts')=0,'reuse copies proof only, never answers/invitations');
insert into pa_state values('reuse',public.process_assessment_workspace(m83_id('a'),m83_id('vacancy'))->'assessment');
update pa_state set value=public.position_assessment_mutate(m83_id('a'),m83_id('vacancy'),null,'allow_ai',(value->>'id')::uuid,(value->>'revision')::integer) where key='reuse';
update pa_state set value=public.position_assessment_mutate(m83_id('a'),m83_id('vacancy'),null,'approve',(value->>'id')::uuid,(value->>'revision')::integer,jsonb_build_object('questionId',m83_id('q1'),'saveToBank',true)) where key='reuse';
insert into pa_state values('approved-bank',public.position_assessment_bank(m83_id('a'),(select (value->>'id')::uuid from pa_state where key='reuse')));
update pa_state set value=public.position_assessment_mutate(m83_id('a'),m83_id('vacancy'),null,'questions',(value->>'id')::uuid,(value->>'revision')::integer,jsonb_build_object('questions',(value->'questions')-0||jsonb_build_array((select value->0 from pa_state where key='approved-bank')))) where key='reuse';
select m83_assert((select value#>>'{questions,9,review}'='approved' and value#>>'{questions,9,approvedBy}'=m83_id('recruiter')::text from pa_state where key='reuse'),'canonical bank version preserves its actual human approval');
update pa_state set value=public.position_assessment_mutate(m83_id('a'),m83_id('vacancy'),null,'questions',(value->>'id')::uuid,(value->>'revision')::integer,jsonb_build_object('questions',(value->'questions')-9||jsonb_build_array((value#>'{questions,9}')||jsonb_build_object('stem','Edited contextual copy')))) where key='reuse';
select m83_assert((select value#>>'{questions,9,review}'='pending' and value#>>'{questions,9,provenance,method}'='human-edited-bank' from pa_state where key='reuse'),'edited bank creates new contextual copy requiring human review');
select set_config('request.jwt.claim.sub',m83_id('member')::text,true);
select m83_reject('select public.process_assessment_workspace(m83_id(''a''),m83_id(''vacancy''))','42501');
select set_config('request.jwt.claim.sub',m83_id('recruiter')::text,true);
select m83_reject('select public.process_assessment_workspace(m83_id(''b''),m83_id(''vacancy''))','42501');
select m83_reject('select private.get_position_follow_up_cycle(m83_id(''a''),m83_id(''vacancy''),null,null)','42501');
select m83_reject('select public.position_assessment_public(''load'',repeat(''a'',64))','42501');
select m83_reject(format('select public.position_assessment_generation_request(%L,%L,%L,%L)',m83_id('a'),(select value->>'id' from pa_state where key='reuse'),m83_id('over-20'),jsonb_build_array(jsonb_build_object('requirementId',m83_id('req'),'difficulty','easy','quantity',21))),'22023');
reset role;
select m83_assert((select profiles from pa_preservation)=(select jsonb_agg(to_jsonb(x)) from public.professional_profiles x),'profiles preserved');
select m83_assert((select matching from pa_preservation) is not distinct from (select jsonb_agg(to_jsonb(x)) from public.match_evaluations x),'matching preserved');
select m83_assert((select positions from pa_preservation)=(select jsonb_agg(to_jsonb(x)) from public.vacancies x),'positions preserved');
do $$ begin begin
 delete from public.people where organization_id=m83_id('a') and id=m83_id('late-person');
 perform m83_assert(not exists(select 1 from public.position_assessment_attempts where person_id=m83_id('late-person')),'explicit person erasure removes own applications');
 perform m83_assert(not exists(select 1 from public.position_assessment_batches b,jsonb_array_elements(b.receipts) r where r->>'personId'=m83_id('late-person')::text),'explicit erasure removes personal batch receipts');
 perform m83_assert(exists(select 1 from public.position_assessments where process_id=(select (value->>'id')::uuid from pa_state where key='process-before')),'erasure of participant preserves common test');
 raise exception 'rollback erasure fixture' using errcode='ZX001';exception when sqlstate 'ZX001' then null;end;end $$;
-- Budget and late-generation proofs use subtransactions and restore the confirmed draft.
do $$ declare a jsonb; g jsonb; p jsonb; q jsonb; begin begin
 a:=public.process_assessment_workspace(m83_id('a'),m83_id('vacancy'))->'assessment';
 a:=public.position_assessment_mutate(m83_id('a'),m83_id('vacancy'),null,'configure',(a->>'id')::uuid,(a->>'revision')::integer,jsonb_build_object('config',jsonb_build_object('quantity',10,'level',1,'durationMinutes',60,'mode','ai'),'requirementIds',jsonb_build_array(m83_id('req'))));
 g:=public.position_assessment_generation_request(m83_id('a'),(a->>'id')::uuid,m83_id('late-generation'),jsonb_build_array(jsonb_build_object('requirementId',m83_id('req'),'difficulty','easy','quantity',1)));
 perform m83_reject(format('select public.position_assessment_mutate(%L,%L,null,''questions'',%L,%s,''{"questions":[]}'')',m83_id('a'),m83_id('vacancy'),a->>'id',a->>'revision'),'40001');
 p:=public.get_position_follow_up(m83_id('a'),m83_id('vacancy'))->'process';
 perform public.mutate_position_follow_up_process(m83_id('a'),m83_id('vacancy'),(p->>'id')::uuid,'close_process',null,(p->>'revision')::integer);
 select value->0 into q from pa_state where key='questions';
 perform m83_reject(format('select public.position_assessment_generation_finish(%L,%L,%L,0.01,true)',m83_id('late-generation'),m83_id('a'),jsonb_build_array(q)),'42501');
 perform m83_assert((public.process_assessment_workspace(m83_id('a'),m83_id('vacancy'))#>'{assessment,questions}')='[]','closed context rejects late generation without overwriting draft');
 raise exception 'rollback generation fixture' using errcode='ZX001';exception when sqlstate 'ZX001' then null;end;
 begin
 a:=public.process_assessment_workspace(m83_id('a'),m83_id('vacancy'))->'assessment';
 a:=public.position_assessment_mutate(m83_id('a'),m83_id('vacancy'),null,'configure',(a->>'id')::uuid,(a->>'revision')::integer,jsonb_build_object('config',jsonb_build_object('quantity',10,'level',1,'durationMinutes',60,'mode','ai'),'requirementIds',jsonb_build_array(m83_id('req'))));
 insert into public.position_assessment_generation(id,organization_id,assessment_id,actor_id,revision,distribution,requirements,status,actual_usd,reserved_usd) values(m83_id('monthly-cap'),m83_id('a'),(a->>'id')::uuid,m83_id('recruiter'),(a->>'revision')::integer,'[]','[]','succeeded',10,0.25);
 perform m83_reject(format('select public.position_assessment_generation_request(%L,%L,%L,%L)',m83_id('a'),a->>'id',m83_id('over-monthly'),jsonb_build_array(jsonb_build_object('requirementId',m83_id('req'),'difficulty','easy','quantity',1))),'22023');
 raise exception 'rollback budget fixture' using errcode='ZX001';exception when sqlstate 'ZX001' then null;end;
end $$;
