-- Synthetic local QA only. No live model, no writes survive.
begin;
do $$ begin if current_database()<>'import_evidence_v202' then raise exception 'Disposable local QA only';end if;end $$;
create function pg_temp.sid(text) returns uuid language sql immutable as $$ select md5('synthesis-fixture-'||$1)::uuid $$;
create function pg_temp.assert(boolean,text) returns void language plpgsql as $$ begin if $1 is distinct from true then raise exception 'FAIL: %',$2; end if; raise notice 'PASS: %',$2; end $$;
create function pg_temp.reject(text,text) returns void language plpgsql as $$ begin begin execute $1; exception when others then if sqlstate=$2 then return; end if; raise exception 'Unexpected rejection %: %',sqlstate,sqlerrm; end; raise exception 'FAIL: accepted forbidden action'; end $$;
insert into public.organization_groups(id,name,slug) values(pg_temp.sid('group'),'Synthesis synthetic','synthesis-synthetic');
insert into public.organizations(id,name,group_id) values(pg_temp.sid('a'),'Synthetic A',pg_temp.sid('group')),(pg_temp.sid('b'),'Synthetic B',pg_temp.sid('group'));
insert into auth.users(id,email) select pg_temp.sid(x),x||'@example.invalid' from unnest(array['owner','member','outsider','inactive']) x;
insert into public.platform_users(id,auth_user_id,full_name,username,email,access_profile,group_id,status)
select pg_temp.sid('platform-'||x),pg_temp.sid(x),'Synthetic '||x,'synthesis-'||x,x||'@example.invalid',(case when x='owner' then 'owner' else 'member' end)::public.membership_role,pg_temp.sid('group'),(case when x='inactive' then 'inactive' else 'active' end)::public.platform_user_status from unnest(array['owner','member','outsider','inactive']) x;
insert into public.organization_memberships(organization_id,user_id,role) values(pg_temp.sid('a'),pg_temp.sid('owner'),'owner'),(pg_temp.sid('a'),pg_temp.sid('member'),'member'),(pg_temp.sid('a'),pg_temp.sid('inactive'),'member'),(pg_temp.sid('b'),pg_temp.sid('outsider'),'member') on conflict do nothing;
insert into public.people(id,organization_id,full_name) values(pg_temp.sid('pa'),pg_temp.sid('a'),'Pessoa sintética A'),(pg_temp.sid('pb'),pg_temp.sid('b'),'Pessoa sintética B');
insert into public.professional_profiles(id,organization_id,person_id,profile_data,extraction_version,inference_version,embedding_version,prompt_version,model_version,profile_version,review_status,approved_at)
values(pg_temp.sid('profile'),pg_temp.sid('a'),pg_temp.sid('pa'),'{"professionalObjective":"Atuar na área financeira","email":"private@example.invalid","phone":"11999999999","fullName":"Não enviar","experiences":[{"id":"experience_synthetic0","role":"Assistente financeiro","organization":"Empresa sintética","description":"Conciliação de extratos e acompanhamento do fluxo de caixa usando Excel"}],"education":[]}','fixture','fixture','none','fixture','fixture',1,'approved',now());
insert into private.profile_synthesis_worker_config(token_hash) values(encode(extensions.digest(repeat('a',64),'sha256'),'hex'));
insert into public.professional_profiles(id,organization_id,person_id,profile_data,extraction_version,inference_version,embedding_version,prompt_version,model_version,profile_version,review_status,approved_at)
values(pg_temp.sid('empty'),pg_temp.sid('b'),pg_temp.sid('pb'),'{}','fixture','fixture','none','fixture','fixture',1,'approved',now()-interval '1 day');
select pg_temp.assert(not(private.profile_synthesis_sources(pg_temp.sid('profile'))::text like '%private@example.invalid%'),'contact and identity excluded');
select pg_temp.assert(jsonb_array_length(private.profile_synthesis_sources(pg_temp.sid('profile')))>0,'published professional sources collected');
set local role authenticated;
select set_config('request.jwt.claim.sub',pg_temp.sid('member')::text,true);
select pg_temp.assert(public.load_profile_synthesis(pg_temp.sid('a'),pg_temp.sid('pa'))->>'state'='not_requested','historical profile read does not enqueue');
select public.request_profile_synthesis(pg_temp.sid('a'),pg_temp.sid('pa')) is not null;
select public.request_profile_synthesis(pg_temp.sid('a'),pg_temp.sid('pa')) is not null;
select pg_temp.reject(format('select public.load_profile_synthesis(%L,%L,%L)',pg_temp.sid('b'),pg_temp.sid('pa'),pg_temp.sid('profile')),'42501');
select pg_temp.reject('select * from public.profile_syntheses','42501');
select set_config('request.jwt.claim.sub',pg_temp.sid('outsider')::text,true);
select pg_temp.assert(public.request_profile_synthesis(pg_temp.sid('b'),pg_temp.sid('pb'))->>'state'='insufficient','empty profile ends explicitly without provider');
select pg_temp.reject(format('select public.load_profile_synthesis(%L,%L)',pg_temp.sid('a'),pg_temp.sid('pa')),'42501');
select set_config('request.jwt.claim.sub',pg_temp.sid('inactive')::text,true);
select pg_temp.reject(format('select public.load_profile_synthesis(%L,%L)',pg_temp.sid('a'),pg_temp.sid('pa')),'42501');
reset role;
insert into public.person_ingestion_events(organization_id,person_id,event_type,result,metadata) values(pg_temp.sid('a'),pg_temp.sid('pa'),'profile_published_merge','success','{"profile_id":"invalid"}');
select pg_temp.assert(exists(select 1 from public.person_ingestion_events where person_id=pg_temp.sid('pa') and metadata->>'profile_id'='invalid'),'optional enqueue failure preserves transactional publication audit');
insert into public.person_ingestion_events(organization_id,person_id,event_type,result,metadata) values(pg_temp.sid('a'),pg_temp.sid('pa'),'profile_published_merge','success',jsonb_build_object('profile_id',pg_temp.sid('profile')));
set local role anon;
select pg_temp.reject(format('select public.load_profile_synthesis(%L,%L)',pg_temp.sid('a'),pg_temp.sid('pa')),'42501');
select pg_temp.reject('select public.claim_profile_synthesis(''invalid'')','42501');
reset role;
select pg_temp.assert((select count(*)=1 from public.profile_synthesis_jobs where person_id=pg_temp.sid('pa')),'repeat request is idempotent');
do $$ declare j jsonb; r jsonb; sources jsonb; id text; a jsonb; begin
 j:=public.claim_profile_synthesis(repeat('a',64));
 perform pg_temp.assert(j is not null,'worker claims job');
 perform pg_temp.assert(public.claim_profile_synthesis(repeat('a',64)) is null,'concurrent claim cannot repeat active lease');
 sources:=j->'sources'; id:=sources->0->>'id';
 select jsonb_agg(jsonb_build_object('questionId',x,'status','insufficient','statements','[]'::jsonb,'missingInformation',jsonb_build_array('Sem informação para este eixo.'))) into a from unnest(array['trajectory','activities','contexts','competencies','results','education','objective','clarifications']) x;
 r:=jsonb_build_object('contractVersion','profile-synthesis-1.1.0','issues','[]'::jsonb,'overview',jsonb_build_array(jsonb_build_object('text','Atuação financeira relatada.','nature','interpretation','sourceIds',jsonb_build_array(id))),'answers',a,'clarifications','[]'::jsonb);
 perform pg_temp.assert(private.valid_profile_synthesis_result(r,sources),'valid response accepted');
 perform pg_temp.assert(private.valid_profile_synthesis_result((r-'issues')||'{"contractVersion":"profile-synthesis-1.0.0"}',sources),'legacy read contract remains valid');
 r:=jsonb_set(jsonb_set(r,'{overview}','[]'),'{issues}','[{"section":"overview","reason":"REFERENCES_INVALID"}]');
 perform pg_temp.assert(private.valid_profile_synthesis_result(r,sources),'partial with unavailable overview accepted');
 perform pg_temp.assert(not private.valid_profile_synthesis_result(jsonb_set(r,'{issues}','[]'),sources),'empty overview must explain unavailable content');
 perform pg_temp.assert(not private.valid_profile_synthesis_result(jsonb_set(r,'{issues}','[{"section":"overview","reason":"private text"}]'),sources),'free text diagnostic rejected');
 r:=jsonb_set(r,'{overview}',jsonb_build_array(jsonb_build_object('text','Atuação financeira relatada.','nature','interpretation','sourceIds',jsonb_build_array(id))));

 perform pg_temp.assert(not private.valid_profile_synthesis_result('{}',sources),'missing keys fail closed');
 perform pg_temp.assert(not private.valid_profile_synthesis_result(r-'overview',sources),'missing overview rejected');
 perform pg_temp.assert(not private.valid_profile_synthesis_result(jsonb_set(r,'{overview,0,sourceIds}','["invented"]'),sources),'invented source rejected');
 perform pg_temp.assert(not private.valid_profile_synthesis_result(jsonb_set(r,'{overview,0,nature}','null'),sources),'null nature rejected');
 perform pg_temp.assert(not private.valid_profile_synthesis_result(jsonb_set(r,'{overview,0,text}',to_jsonb('Unsafe'||chr(1))),sources),'unsafe text rejected server side');
 perform pg_temp.assert(not private.valid_profile_synthesis_result(jsonb_set(r,'{overview,0,text}','"Competência verificada por Assessment."'),sources),'unsupported verification rejected server side');
 perform pg_temp.assert(not private.valid_profile_synthesis_result(jsonb_set(r,'{overview,0,sourceIds}',jsonb_build_array(id,id)),sources),'duplicate source rejected');
 perform pg_temp.reject(format('select public.complete_profile_synthesis(%L,%L,%L,%L,%L,10,20,30)',repeat('a',64),j->>'id',gen_random_uuid(),r,'fixture'),'40001');
 perform public.complete_profile_synthesis(repeat('a',64),(j->>'id')::uuid,(j->>'lease')::uuid,r,'gpt-5.6-luna',10,20,30);
 perform pg_temp.assert((select count(*)=1 from public.profile_syntheses where person_id=pg_temp.sid('pa')),'single immutable persisted synthesis');
 perform pg_temp.assert(public.claim_profile_synthesis(repeat('a',64)) is null,'complete and empty analyses do not call provider again');
 perform set_config('request.jwt.claim.sub',pg_temp.sid('member')::text,true);
 r:=public.load_profile_synthesis(pg_temp.sid('a'),pg_temp.sid('pa'));
 perform pg_temp.assert(r->>'state'='complete' and r#>>'{result,issues,0,section}'='overview','partial result and per-section reason returned');
 perform pg_temp.assert(not (r#>'{sources,0}' ? 'text'),'source body omitted from common read');
 perform pg_temp.assert(public.load_profile_synthesis_source(pg_temp.sid('a'),pg_temp.sid('pa'),(r->>'analysisId')::uuid,id)->>'text' is not null,'source detail loads on demand');
 perform pg_temp.reject(format('select public.load_profile_synthesis_source(%L,%L,%L,%L)',pg_temp.sid('b'),pg_temp.sid('pb'),r->>'analysisId',id),'42501');
 update public.professional_profiles p set profile_data=jsonb_set(profile_data,'{professionalObjective}','"Atuar em controles financeiros"') where p.id=pg_temp.sid('profile');
 r:=public.request_profile_synthesis(pg_temp.sid('a'),pg_temp.sid('pa'));
 perform pg_temp.assert(r->>'state'='queued' and r->'previous'<>'null'::jsonb,'changed basis retains labeled prior analysis');
 j:=public.claim_profile_synthesis(repeat('a',64));
 perform public.complete_profile_synthesis(repeat('a',64),(j->>'id')::uuid,(j->>'lease')::uuid,null,'gpt-5.6-luna',0,0,1,'RATE_LIMITED');
 perform pg_temp.assert((select state='queued' and attempts=1 from public.profile_synthesis_jobs jobs where jobs.id=(j->>'id')::uuid),'transient failure retried without new job');
 update public.profile_synthesis_jobs jobs set state='processing',attempts=3,lease=gen_random_uuid(),lease_until=now()-interval '1 minute' where jobs.id=(j->>'id')::uuid;
 perform public.claim_profile_synthesis(repeat('a',64));
 perform pg_temp.assert((select state='failed' from public.profile_synthesis_jobs jobs where jobs.id=(j->>'id')::uuid),'exhausted expired lease ends instead of hanging');
end $$;
-- Diagnostic/recovery delta; published facts and prior analyses remain authoritative.
do $$ declare j jsonb; v jsonb; d jsonb; begin
 perform set_config('request.jwt.claim.sub',pg_temp.sid('member')::text,true);
 v:=public.load_profile_synthesis(pg_temp.sid('a'),pg_temp.sid('pa'));
 perform pg_temp.assert(v->>'attempts'='3' and not (v->>'canRetry')::boolean,'exhausted job cannot restart its budget');
 perform public.retry_profile_synthesis(pg_temp.sid('a'),pg_temp.sid('pa'));
 perform pg_temp.assert((public.load_profile_synthesis(pg_temp.sid('a'),pg_temp.sid('pa'))->>'attempts')::integer=3,'retry does not reset exhausted attempts');
 update public.professional_profiles set profile_data=jsonb_set(profile_data,'{professionalObjective}','"Atuação com controles e relatórios"') where id=pg_temp.sid('profile');
 perform public.request_profile_synthesis(pg_temp.sid('a'),pg_temp.sid('pa'));
 j:=public.claim_profile_synthesis(repeat('a',64));
 d:=jsonb_build_object('version','synthesis-diagnostic-1.0.0','stage','contract','reason','WORD_LIMIT','section','overview','observed',121,'limit',120);
 perform pg_temp.reject(format('select public.complete_profile_synthesis(%L,%L,%L,null,%L,100,200,300,%L,%L)',repeat('a',64),j->>'id',j->>'lease','gpt-5.6-luna','RESPONSE_INVALID',d||'{"private":"personal content"}'::jsonb),'22023');
 perform pg_temp.reject(format('select public.complete_profile_synthesis(%L,%L,%L,null,%L,100,200,300,%L,%L)',repeat('a',64),j->>'id',j->>'lease','gpt-5.6-luna','RESPONSE_INVALID',jsonb_set(d,'{reason}','"personal content"')),'22023');
 perform public.complete_profile_synthesis(repeat('a',64),(j->>'id')::uuid,(j->>'lease')::uuid,null,'gpt-5.6-luna',100,200,300,'RESPONSE_INVALID',d);
 perform pg_temp.assert((select input_tokens=100 and output_tokens=200 and diagnostic=d from public.profile_synthesis_attempts where job_id=(j->>'id')::uuid and attempt=1),'rejected response keeps metrics and safe diagnostic');
 v:=public.load_profile_synthesis(pg_temp.sid('a'),pg_temp.sid('pa'));
 perform pg_temp.assert(v->>'state'='failed' and v->>'jobId'=j->>'id' and v->'diagnostic'=d and v->'previous'<>'null'::jsonb,'failed current synthesis returns reason and preserves prior');
 perform public.retry_profile_synthesis(pg_temp.sid('a'),pg_temp.sid('pa'));
 perform pg_temp.assert(public.claim_profile_synthesis(repeat('a',64)) is null,'retry honors cooldown');
 update public.profile_synthesis_jobs set available_at=now()-interval '1 minute' where id=(j->>'id')::uuid;
 perform set_config('request.jwt.claim.sub',pg_temp.sid('outsider')::text,true);
 perform pg_temp.reject(format('select public.retry_profile_synthesis(%L,%L)',pg_temp.sid('a'),pg_temp.sid('pa')),'42501');
 perform set_config('request.jwt.claim.sub',pg_temp.sid('inactive')::text,true);
 perform pg_temp.reject(format('select public.retry_profile_synthesis(%L,%L)',pg_temp.sid('a'),pg_temp.sid('pa')),'42501');
 perform set_config('request.jwt.claim.sub',pg_temp.sid('member')::text,true);
 perform public.retry_profile_synthesis(pg_temp.sid('a'),pg_temp.sid('pa'));
 perform public.retry_profile_synthesis(pg_temp.sid('a'),pg_temp.sid('pa'));
 perform pg_temp.assert((select state='queued' and attempts=1 from public.profile_synthesis_jobs where id=(j->>'id')::uuid),'repeat recovery preserves one job and attempt count');
 j:=public.claim_profile_synthesis(repeat('a',64));
 perform pg_temp.assert((select attempts=2 from public.profile_synthesis_jobs where id=(j->>'id')::uuid),'recovery claims exactly next attempt');
 perform public.complete_profile_synthesis(repeat('a',64),(j->>'id')::uuid,(j->>'lease')::uuid,'{}','gpt-5.6-luna',100,200,300);
 v:=public.load_profile_synthesis(pg_temp.sid('a'),pg_temp.sid('pa'));
 perform pg_temp.assert(v->>'state'='failed' and v#>>'{diagnostic,reason}'='DATABASE_CONTRACT','database validation failure recorded instead of leaving a hanging lease');
 perform pg_temp.assert(not (v->>'canRetry')::boolean,'internal persistence problem does not offer useless recovery');
 perform pg_temp.assert((select count(*)=2 from public.profile_synthesis_attempts where job_id=(j->>'id')::uuid),'old attempt history preserved');
end $$;
set local role anon;
select pg_temp.reject(format('select public.retry_profile_synthesis(%L,%L)',pg_temp.sid('a'),pg_temp.sid('pa')),'42501');
reset role;


insert into public.people(id,organization_id,full_name) values(pg_temp.sid('legacy-person'),pg_temp.sid('a'),'Pessoa legada sintética');
insert into public.professional_profiles(id,organization_id,person_id,profile_data,extraction_version,inference_version,embedding_version,prompt_version,model_version,profile_version,review_status,approved_at)
values(pg_temp.sid('legacy-profile'),pg_temp.sid('a'),pg_temp.sid('legacy-person'),'{"professionalObjective":"Atuar na área financeira"}','fixture','fixture','none','fixture','fixture',1,'approved',now());
insert into public.profile_synthesis_jobs(organization_id,person_id,profile_id,basis_hash,state,attempts,error_code,contract_version,prompt_version)
values(pg_temp.sid('a'),pg_temp.sid('legacy-person'),pg_temp.sid('legacy-profile'),encode(extensions.digest(private.profile_synthesis_sources(pg_temp.sid('legacy-profile'))::text,'sha256'),'hex'),'failed',3,'RESPONSE_INVALID','profile-synthesis-1.0.0','profile-synthesis-prompt-1.0.0');
select set_config('request.jwt.claim.sub',pg_temp.sid('member')::text,true);
set local role authenticated;
select pg_temp.assert((public.load_profile_synthesis(pg_temp.sid('a'),pg_temp.sid('legacy-person'))->>'canRetry')::boolean,'old exhausted response can explicitly request corrected contract');
select pg_temp.assert(public.retry_profile_synthesis(pg_temp.sid('a'),pg_temp.sid('legacy-person'))->>'state'='queued','explicit recovery queues corrected contract');
select public.retry_profile_synthesis(pg_temp.sid('a'),pg_temp.sid('legacy-person'));
reset role;
select pg_temp.assert((select count(*)=2 from public.profile_synthesis_jobs where person_id=pg_temp.sid('legacy-person')),'recovery replay creates only one new versioned job');
select pg_temp.assert((select attempts=3 and state='failed' from public.profile_synthesis_jobs where person_id=pg_temp.sid('legacy-person') and contract_version='profile-synthesis-1.0.0'),'legacy budget and failure preserved');
select pg_temp.assert((select attempts=0 and contract_version='profile-synthesis-1.1.0' from public.profile_synthesis_jobs where person_id=pg_temp.sid('legacy-person') and contract_version='profile-synthesis-1.1.0'),'corrected contract owns distinct bounded budget');

delete from public.people where id=pg_temp.sid('pa');
select pg_temp.assert(not exists(select 1 from public.profile_syntheses where person_id=pg_temp.sid('pa')) and not exists(select 1 from public.profile_synthesis_jobs where person_id=pg_temp.sid('pa')) and not exists(select 1 from public.profile_synthesis_attempts where person_id=pg_temp.sid('pa')),'person deletion cascades derived data and attempts');
rollback;
