import test from "node:test";
import assert from "node:assert/strict";
import {withAiHistory,recordAiCacheHit,type AiHistoryClient} from "../src/infrastructure/aiHistory.js";
const scope={organizationId:"00000000-0000-4000-8000-000000000001",functionName:"parser_ia",operationId:"00000000-0000-4000-8000-000000000002",sourceVersion:"fixture-1.0.0",inputFingerprint:"a".repeat(64)};
function ledger(fail:string|null=null){const calls:Array<{action:string;data:Record<string,unknown>}>=[];const client:AiHistoryClient={rpc:async(_name,args)=>{const action=String(args.p_action),data=args.p_data as Record<string,unknown>;calls.push({action,data});return {data:action==="open_request"?{request:{id:scope.operationId}}:{acquired:true},error:action===fail?{code:"fake"}:null};}};return {calls,client};}
const providerBody=JSON.stringify({model:"gpt-5.6-luna",store:false,input:"private fixture not to store"});
test("history is committed before external I/O; parallel requests retain separate usage and never persist input",async()=>{const l=ledger();let io=0;await withAiHistory(l.client,scope,async fetcher=>Promise.all([fetcher("https://api.openai.com/v1/responses",{body:providerBody}),fetcher("https://api.openai.com/v1/responses",{body:providerBody})]),async()=>{io++;assert.equal(l.calls.filter(c=>c.action==="begin_attempt").length,2);return Response.json({usage:{input_tokens:100,output_tokens:20}});});assert.equal(io,2);const events=l.calls.filter(c=>c.action==="complete_attempt");assert.equal(events.length,2);assert.notEqual(events[0]?.data.attemptId,events[1]?.data.attemptId);assert.equal(events[0]?.data.estimatedCostUsd,0.000044);assert.equal(events[0]?.data.observedCostUsd,null);assert.equal(l.calls.at(-1)?.data.status,"succeeded");assert.ok(!JSON.stringify(l.calls).includes("private fixture"));});
test("missing usage and web tool costs remain unknown, never zero",async()=>{for(const body of [providerBody,JSON.stringify({model:"gpt-5.6-luna",tools:[{type:"web_search"}]})]){const l=ledger();await withAiHistory(l.client,scope,f=>f("https://api.openai.com/v1/responses",{body}),async()=>Response.json({}));const event=l.calls.find(c=>c.action==="complete_attempt")?.data;assert.equal(event?.inputTokens,null);assert.equal(event?.outputTokens,null);assert.equal(event?.estimatedCostUsd,null);}});
test("provider failure and failed validation preserve incurred usage and logical failure",async()=>{for(const mode of ["http","invalid","transport"]){const l=ledger();try{await withAiHistory(l.client,scope,async f=>{const r=await f("https://api.openai.com/v1/responses",{body:providerBody});if(!r.ok||mode==="invalid")throw Error("fixture validation");return r;},async()=>{if(mode==="transport")throw Error("transport");return Response.json({usage:{input_tokens:10,output_tokens:2}},{status:mode==="http"?500:200});});assert.fail();}catch{const event=l.calls.find(c=>c.action==="complete_attempt")?.data;assert.equal(event?.result,mode==="invalid"?"success":"failure");assert.equal(event?.inputTokens,mode==="transport"?null:10);assert.equal(l.calls.at(-1)?.data.status,"failed");}}});
test("unavailable mandatory ledger prevents provider call",async()=>{for(const phase of ["open_request","begin_attempt"]){let io=false;await assert.rejects(()=>withAiHistory(ledger(phase).client,scope,f=>f("https://api.openai.com/v1/responses",{body:providerBody}),async()=>{io=true;return Response.json({});}),/AI_HISTORY/);assert.equal(io,false);}});
test("cache hit is explicitly zero external cost with unknown tokens and no fetch",async()=>{const l=ledger();await recordAiCacheHit(l.client,scope,15);const event=l.calls.find(c=>c.action==="complete_attempt")?.data;assert.equal(event?.estimatedCostUsd,0);assert.equal(event?.inputTokens,null);assert.equal(event?.outputTokens,null);assert.equal(event?.durationMs,15);assert.equal(l.calls.at(-1)?.data.status,"succeeded");});
