import assert from "node:assert/strict";
import {createRequire} from "node:module";
import {mkdir,writeFile} from "node:fs/promises";
const {chromium}=createRequire(import.meta.url)(process.env.PRISMA_PLAYWRIGHT_PATH??"playwright");
const browser=await chromium.launch({headless:true,executablePath:process.env.PRISMA_BROWSER_PATH});
const base="http://127.0.0.1:5696",dir="docs/qa/evidence/loading-feedback-v216",results=[];
await mkdir(dir,{recursive:true});
const coreOnly=process.env.PRISMA_LOADING_CORE_ONLY==="1",authOnly=process.env.PRISMA_LOADING_AUTH_ONLY==="1";
const pages=authOnly?["PrismaApplication"]:coreOnly?[]:["HomePage","PeoplePage","PersonWorkspacePage","PersonProfilePage","PersonFormPage","PersonMergePage","DocumentDetailPage","DocumentOperationsPage","ProfileComparePage","ProfileDeltaPage","ProfileReviewPage","ProfileVersionsPage","SettingsPage","KnowledgePage","UsersPage","UserFormPage","AssessmentItemBankPage","CompetencyVerificationPage","VerificationOperationsPage","VerificationSessionPage","PersonDataSelfServicePage","VacanciesPage","VacancyEditorPage","VacancyDetailPage","VacancyPeoplePage","VacancyComparePage"];
async function open(name,width=1280){const p=await browser.newPage({viewport:{width,height:980}}),errors=[],external=[];p.on("pageerror",e=>errors.push(e.message));await p.route("**/*",r=>r.request().url().startsWith(base+"/")?r.continue():(external.push(r.request().url()),r.abort()));await p.goto(`${base}/loading-feedback.html?page=${name}`);await p.getByRole("button",{name:"Desmontar tela",exact:true}).waitFor();return {p,errors,external};}
try{
 for(const name of pages){const {p,errors,external}=await open(name);const busy=p.locator(".prisma-loading-feedback");await busy.waitFor({state:"visible"});assert.equal(await busy.getAttribute("aria-busy"),"true");
  if(["KnowledgePage","PersonWorkspacePage","VacancyPeoplePage"].includes(name))await p.screenshot({path:`${dir}/${name}-1280.png`,fullPage:true});
  await p.evaluate(()=>window.__loadingFixture.fail());await busy.waitFor({state:"hidden"});
  await p.getByRole("button",{name:"Desmontar tela",exact:true}).click();await busy.waitFor({state:"hidden"});
  results.push({name,initialVisible:true,errorSettles:true,unmountSettles:true,errors,external});assert.equal(errors.length,0,JSON.stringify(results.at(-1)));assert.equal(external.length,0);await p.close();
 }
 for(const name of (coreOnly||authOnly)?[]:["ResumeImportPage","ProfileSearchPage","PasswordChangePage","VacancyAssistPage"]){const {p,errors,external}=await open(name);await p.waitForTimeout(200);assert.equal(await p.locator('.prisma-loading-feedback').isVisible(),false);if(name==="ProfileSearchPage"){await p.getByRole("button",{name:/Encontrar pessoas|Buscar pessoas|Buscar perfis/i}).last().click();await p.locator('.prisma-loading-feedback').waitFor({state:"visible"});await p.evaluate(()=>window.__loadingFixture.fail());await p.locator('.prisma-loading-feedback').waitFor({state:"hidden"});}results.push({name,idleNoFalseLoading:true,errors,external});assert.equal(errors.length,0,JSON.stringify(results.at(-1)));assert.equal(external.length,0);await p.close();}
 for(const width of authOnly?[]:[1280,390,320]){const {p,errors,external}=await open("Core",width);const busy=p.locator('.prisma-loading-feedback');await p.getByRole('button',{name:'Atualizar',exact:true}).click();await busy.waitFor({state:'visible'});await p.getByRole('button',{name:'Atualizar',exact:true}).click();await p.getByRole('button',{name:'Calcular',exact:true}).click();
  await p.getByRole('textbox',{name:'Rascunho'}).fill('Edição durante carregamento');await p.evaluate(()=>window.__loadingFixture.pending.shift().resolve(null));assert.equal(await busy.isVisible(),true);await p.evaluate(()=>window.__loadingFixture.pending.shift().resolve(null));assert.equal(await busy.isVisible(),true);assert.match(await busy.innerText(),/Calculando resultado/);
  assert.equal(await p.getByRole('textbox',{name:'Rascunho'}).inputValue(),'Edição durante carregamento');assert.equal(await p.getByText('Score salvo: 73/100',{exact:true}).isVisible(),true);await p.screenshot({path:`${dir}/concurrent-${width}.png`,fullPage:true});await p.evaluate(()=>window.__loadingFixture.fail());await busy.waitFor({state:'hidden'});await p.getByRole('alert').waitFor();
  await p.getByRole('button',{name:'Abrir modal'}).click();await busy.waitFor({state:'visible'});await p.getByRole('dialog').waitFor({state:'visible'});await p.waitForTimeout(300);await p.getByRole('dialog').press('Escape');await busy.waitFor({state:'hidden'});await p.getByRole('button',{name:'Alternar bloco'}).click();await busy.waitFor({state:'visible'});await p.getByRole('button',{name:'Desmontar tela'}).click();await busy.waitFor({state:'hidden'});
  assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);results.push({name:'Core',width,concurrentTasks:true,previousContentAndDraftPreserved:true,errorRecovery:true,modalCloseAndUnmount:true,noOverflow:true,errors,external});assert.equal(errors.length,0,JSON.stringify(results.at(-1)));assert.equal(external.length,0);await p.close();
 }
}finally{await writeFile(dir+(authOnly?'/browser-auth-results.json':coreOnly?'/browser-core-results.json':'/browser-results.json'),JSON.stringify(results,null,2)+'\n');await browser.close();}
console.log(JSON.stringify({scenarios:results.length,passed:true}));
