import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {mkdir,writeFile} from 'node:fs/promises';
const {chromium}=createRequire(import.meta.url)(process.env.PRISMA_PLAYWRIGHT_PATH??'playwright');
const browser=await chromium.launch({headless:true,executablePath:process.env.PRISMA_BROWSER_PATH});
const base='http://127.0.0.1:5697',dir=process.env.PRISMA_FOLLOW_UP_EVIDENCE??'docs/qa/evidence/follow-up-stages';await mkdir(dir,{recursive:true});const results=[];
async function check(name,value){results.push({name,pass:Boolean(value)});await writeFile(`${dir}/browser-results.json`,JSON.stringify(results,null,2));assert.ok(value,name);}
async function select(p,name,label){await p.getByRole('combobox',{name,exact:true}).click();await p.locator('.ant-select-dropdown:visible').getByText(label,{exact:true}).click();}
async function drag(p,person,column,{escape=false,screenshot}={}){const handle=p.getByRole('button',{includeHidden:true,name:`Arrastar ${person}`,exact:true}),source=await handle.boundingBox(),dest=await p.locator(`[data-column="${column}"]`).boundingBox();assert.ok(source&&dest);await p.mouse.move(source.x+source.width/2,source.y+source.height/2);await p.mouse.down();await p.mouse.move(source.x+15,source.y+15,{steps:8});await p.mouse.move(Math.min(dest.x+dest.width/2,p.viewportSize().width-60),dest.y+70,{steps:18});await p.waitForTimeout(120);if(screenshot)await p.screenshot({path:`${dir}/${screenshot}`,fullPage:true});if(escape)await p.keyboard.press('Escape');await p.mouse.up();await p.waitForTimeout(230);}
try{
 const p=await browser.newPage({viewport:{width:1448,height:980}}),errors=[],external=[];
 p.on('pageerror',e=>{errors.push(e.message);console.log('Runtime error:',e.message);});await p.route('**/*',r=>r.request().url().startsWith(base+'/')?r.continue():(external.push(r.request().url()),r.abort()));
 await p.goto(`${base}/position-follow-up.html`);await p.getByRole('button',{includeHidden:true,name:'Marina Costa',exact:true}).waitFor();
 await p.screenshot({path:`${dir}/kanban-desktop.png`,fullPage:true});
 await check('compact card numeric score without age or denominator',await p.locator('.pf-card').count()===4&&!(await p.locator('.pf-card').allTextContents()).join('').includes('/100')&&!(await p.locator('[data-entry$="000000000010"]').textContent()).includes('anos'));
 await check('five columns merge both legacy stages without redundant status tags',await p.locator('.pf-column').count()===5&&await p.locator('[data-column="awaiting_evaluation"] .pf-card').count()===2&&await p.locator('[data-column="interview_scheduled"] .pf-card').count()===1&&await p.locator('.pf-card .ant-tag').count()===0&&!(await p.locator('body').innerText()).includes('Aguardando avaliação')&&!(await p.locator('body').innerText()).includes('Em avaliação'));
 const boxes=await p.locator('.pf-column').evaluateAll(nodes=>nodes.map(n=>({width:n.getBoundingClientRect().width,height:n.getBoundingClientRect().height})));await check('all columns have equal dimensions',boxes.every(b=>Math.abs(b.width-boxes[0].width)<1&&Math.abs(b.height-boxes[0].height)<1));
 await select(p,'Filtrar etapa','Selecionadas para acompanhamento');await check('initial phase filter includes both legacy stages',await p.locator('.pf-card').count()===2);await select(p,'Filtrar etapa','Todas as etapas');
 const callsBeforeForm=await p.evaluate(()=>window.__followUpFixture.calls.filter(c=>c.name==='mutate_position_follow_up').length);
 await drag(p,'Marina Costa','interview_scheduled');await p.getByRole('dialog').waitFor();await p.waitForTimeout(400);await check('drag to scheduled opens interview form without mutation',await p.getByLabel('Data e hora da entrevista').evaluate(n=>document.activeElement===n)&&await p.evaluate(()=>window.__followUpFixture.calls.filter(c=>c.name==='mutate_position_follow_up').length)===callsBeforeForm);await p.getByRole('button',{includeHidden:true,name:'Fechar',exact:true}).click();await p.getByRole('dialog').waitFor({state:'detached'});
 await select(p,'Mover etapa de Marina Costa','Decisão registrada');await p.getByRole('dialog').waitFor();await p.waitForFunction(()=>document.activeElement?.getAttribute('value')==='proceed');await check('move to decision opens unselected form without mutation',await p.getByRole('radio',{name:'Prosseguir',exact:true}).evaluate(n=>document.activeElement===n&&!n.checked)&&await p.evaluate(()=>window.__followUpFixture.calls.filter(c=>c.name==='mutate_position_follow_up').length)===callsBeforeForm);await p.getByRole('button',{includeHidden:true,name:'Fechar',exact:true}).click();await p.getByRole('dialog').waitFor({state:'detached'});
 const baseline=await p.evaluate(()=>window.__followUpFixture.data.entries.map(e=>[e.personId,e.score,e.match.score]));
 await drag(p,'Marina Costa','awaiting_interview',{escape:true});
 await check('Escape cancels drag without mutation',await p.evaluate(()=>window.__followUpFixture.calls.filter(c=>c.name==='mutate_position_follow_up').length)===0);
 await drag(p,'Marina Costa','awaiting_interview',{screenshot:'drag-desktop.png'});
 await check('real mouse drag moves only chosen card',await p.evaluate(()=>window.__followUpFixture.data.entries.find(e=>e.fullName==='Marina Costa').stage)==='awaiting_interview');
 await check('drag never schedules an interview',await p.evaluate(()=>!window.__followUpFixture.data.entries.find(e=>e.fullName==='Marina Costa').details.interview));
 const move=p.getByRole('combobox',{name:'Mover etapa de Marina Costa',exact:true});await move.focus();await move.press('ArrowDown');await move.press('Enter');await p.waitForTimeout(220);
 await check('accessible move alternative saves stage',await p.evaluate(()=>window.__followUpFixture.data.entries.find(e=>e.fullName==='Marina Costa').stage)==='awaiting_evaluation');
 await p.evaluate(()=>{window.__followUpFixture.fail=true;});await drag(p,'Marina Costa','awaiting_interview');
 await check('failure keeps confirmed stage',await p.locator('[data-column="awaiting_evaluation"] .pf-card').filter({hasText:'Marina Costa'}).count()===1&&await p.getByText(/último estado confirmado/).isVisible());
 await p.evaluate(()=>{window.__followUpFixture.fail=false;window.__followUpFixture.conflict=true;});await drag(p,'Marina Costa','awaiting_decision');
 await check('conflict keeps confirmed stage and informs operator',await p.getByText(/Outra pessoa alterou este acompanhamento/).isVisible()&&await p.locator('[data-column="awaiting_evaluation"] .pf-card').filter({hasText:'Marina Costa'}).count()===1);
 await p.getByRole('button',{includeHidden:true,name:'Marina Costa',exact:true}).click();await p.getByRole('dialog').waitFor();
 await check('decision starts with no selected outcome',await p.getByRole('dialog').getByRole('radio').count()===2&&await p.getByRole('dialog').getByRole('radio').evaluateAll(nodes=>nodes.every(n=>!n.checked)));
 await p.getByLabel('Próxima ação',{exact:true}).fill('Revisar experiência em APIs');await p.getByLabel('Anotações e perguntas internas').fill('Perguntar sobre observabilidade.');
 await p.getByRole('button',{includeHidden:true,name:'Salvar acompanhamento',exact:true}).click();await p.waitForFunction(()=>window.__followUpFixture.data.entries.find(e=>e.fullName==='Marina Costa').revision>=4);await p.locator('.pf-drawer .ant-btn-loading').waitFor({state:'detached'});
 await p.getByText('Registrar decisão',{exact:true}).scrollIntoViewIfNeeded();await p.locator('.pf-drawer button').filter({hasText:/^Registrar decisão$/}).click();await check('rationale and decision required',await p.getByText('Escolha a decisão e informe sua justificativa.',{exact:true}).isVisible());
 await p.getByRole('button',{name:'Revisar campos',exact:true}).click();await check('validation notice focuses decision field without changing draft',await p.getByRole('radio',{name:'Prosseguir',exact:true}).evaluate(n=>document.activeElement===n)&&await p.getByLabel('Próxima ação',{exact:true}).inputValue()==='Revisar experiência em APIs');
 await p.getByLabel('Data e hora da entrevista').fill('2026-10-15T14:00');await p.getByLabel('Participantes',{exact:true}).fill('Marina Costa e Bruno');await p.locator('.pf-drawer button').filter({hasText:/^Agendar entrevista$/}).click();await p.waitForTimeout(220);
 await check('explicit interview persisted with zone',await p.evaluate(()=>window.__followUpFixture.data.entries.find(e=>e.fullName==='Marina Costa').details.interview.at)==='2026-10-15T17:00:00.000Z');
 await check('saved interview appears in its own column',await p.locator('[data-column="interview_scheduled"] .pf-card').filter({hasText:'Marina Costa'}).count()===1);await p.locator('.pf-drawer button').filter({hasText:/^Cancelar entrevista$/}).click();await p.waitForTimeout(220);
 await p.getByRole('radio',{name:'Prosseguir',exact:true}).check();await p.getByLabel('Justificativa obrigatória').fill('Aprofundar evidências em conversa técnica.');await p.getByText('Registrar decisão',{exact:true}).scrollIntoViewIfNeeded();await p.locator('.pf-drawer button').filter({hasText:/^Registrar decisão$/}).click();await p.waitForTimeout(220);
 await check('human decision preserved separately',await p.evaluate(()=>window.__followUpFixture.data.entries.find(e=>e.fullName==='Marina Costa').stage)==='decision_recorded');
 await check('saved decision appears in its own column',await p.locator('[data-column="decision_recorded"] .pf-card').filter({hasText:'Marina Costa'}).count()===1);await p.getByLabel('Anotações e perguntas internas').fill('Rascunho ainda não salvo');await p.getByRole('button',{includeHidden:true,name:'Fechar',exact:true}).click();await p.getByRole('button',{includeHidden:true,name:'Continuar editando',exact:true}).click();
 await check('drawer close protects unsaved draft',await p.getByLabel('Anotações e perguntas internas').inputValue()==='Rascunho ainda não salvo');
 await p.getByRole('button',{includeHidden:true,name:'Fechar',exact:true}).click();await p.getByRole('button',{includeHidden:true,name:'Descartar e fechar',exact:true}).click();await p.waitForTimeout(150);
 await p.getByText('Lista',{exact:true}).click();await p.getByRole('cell',{name:'Revisar experiência em APIs',exact:true}).waitFor();await p.screenshot({path:`${dir}/list-desktop.png`,fullPage:true});
 await p.getByRole('textbox',{name:'Buscar Pessoa ou próxima ação',exact:true}).fill('APIs');await check('list filter by next action',await p.getByRole('row').count()===2);await p.getByText('Kanban',{exact:true}).click();await check('view switch preserves filters',await p.locator('.pf-card').count()===1);
 await p.getByRole('textbox',{name:'Buscar Pessoa ou próxima ação',exact:true}).fill('');
 await check('all follow-up mutations preserve scores',JSON.stringify(baseline)===JSON.stringify(await p.evaluate(()=>window.__followUpFixture.data.entries.map(e=>[e.personId,e.score,e.match.score]))));
 await p.getByText('Encontrar pessoas',{exact:true}).scrollIntoViewIfNeeded();await p.locator('button').filter({hasText:/^Encontrar pessoas$/}).click();await p.evaluate(()=>{window.__followUpFixture.fail=true;});await p.locator('.prisma-add-to-evaluation button').filter({hasText:/^Adicionar ao acompanhamento$/}).first().click();await p.getByRole('button',{name:'Tentar novamente',exact:true}).waitFor();await p.evaluate(()=>{window.__followUpFixture.fail=false;});await p.getByRole('button',{name:'Tentar novamente',exact:true}).click();await check('inclusion notice retries explicit action',true);await p.locator('.prisma-add-to-evaluation button').filter({hasText:/^Pessoa adicionada ao acompanhamento$/}).waitFor();await check('explicit inclusion independent of comparison',await p.locator('button').filter({hasText:/Comparar selecionadas \(0\/2\)/}).isDisabled());await p.getByRole('button',{includeHidden:true,name:'Acompanhamento',exact:true}).click();await p.getByRole('button',{includeHidden:true,name:'Marina Costa',exact:true}).waitFor();
 await check('no runtime errors or external calls',errors.length===0&&external.length===0);await p.close();
 for(const scenario of ['normal','missing','empty','member','legacy']){
  const q=await browser.newPage({viewport:{width:390,height:844}});await q.goto(`${base}/position-follow-up.html?case=${scenario}`);
  if(scenario==='member'){await q.getByText('Você não tem acesso ao acompanhamento desta Posição.',{exact:true}).waitFor();await check('member cannot render board',await q.locator('.pf-card').count()===0);}
  else if(scenario==='empty'){await q.getByText('Nenhuma Pessoa foi adicionada ao acompanhamento desta Posição.',{exact:true}).waitFor();await check('empty state retains explicit discovery entry',await q.locator('button').filter({hasText:/^Encontrar pessoas$/}).count()===2);}
  else {await q.getByRole('button',{includeHidden:true,name:'Marina Costa',exact:true}).waitFor({state:'attached'});await select(q,'Coluna do Kanban','Selecionadas para acompanhamento (2)');await q.getByRole('button',{includeHidden:true,name:'Marina Costa',exact:true}).waitFor();await check(`${scenario}: mobile single column, readable without horizontal scroll`,await q.locator('.pf-column:visible').count()===1&&await q.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));if(scenario==='legacy'){await check('legacy mobile column and filter remain visible',await q.locator('.pf-column:visible').getAttribute('data-column')==='awaiting_evaluation'&&await q.locator('.pf-column:visible .pf-card').count()===2);}else if(scenario==='normal'){await q.getByRole("heading",{name:"Coordenação de Operações",exact:true}).click();await q.waitForTimeout(450);await q.screenshot({path:`${dir}/kanban-mobile.png`,fullPage:true});await q.getByRole('button',{includeHidden:true,name:'Marina Costa',exact:true}).click();await q.getByRole('dialog').waitFor();await q.waitForTimeout(600);await q.screenshot({path:`${dir}/detail-mobile.png`});await check('mobile drawer full viewport',Math.abs((await q.getByRole('dialog').boundingBox()).width-390)<3&&Math.abs((await q.getByRole('dialog').boundingBox()).x)<3);}else {await check('missing data honest',await q.locator('.pf-card').filter({hasText:'Rafael Lima'}).locator('.pf-score').getAttribute('aria-label').then(v=>v.includes('Indisponível'))&&await q.getByText('Cargo não informado',{exact:true}).isVisible());}}
  await q.close();
 }
}catch(error){const page=browser.contexts()[0]?.pages()[0];if(page){await page.screenshot({path:`${dir}/failure.png`,fullPage:true});console.log((await page.locator('body').innerText()).slice(-3000));}throw error;}finally{await browser.close();}
console.log(JSON.stringify(results,null,2));
