import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {mkdir,writeFile} from 'node:fs/promises';
const {chromium}=createRequire(import.meta.url)(process.env.PRISMA_PLAYWRIGHT_PATH??'playwright');const browser=await chromium.launch({headless:true,executablePath:process.env.PRISMA_BROWSER_PATH});
const base='http://127.0.0.1:5710',dir='docs/qa/evidence/process-assessment-v232/browser',checks=[];await mkdir(dir,{recursive:true});
const check=(name,value)=>{checks.push({name,pass:!!value});assert.ok(value,name);};
async function open(page,state){await page.goto(`${base}/process-assessment.html?state=${state}`);await page.getByRole('heading',{name:state==='follow-up'?'Coordenação de Operações':'Avaliação do processo',exact:true}).waitFor();await page.waitForTimeout(150);}
const calls=page=>page.evaluate(()=>window.__processFixture.calls);
try {
 for(const width of [1448,768,390,320]){
  const page=await browser.newPage({viewport:{width,height:980}}),errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>r.request().url().startsWith(base+'/')?r.continue():(external.push(r.request().url()),r.abort()));
  await open(page,'follow-up');await page.getByRole('checkbox',{name:'Selecionar Rafael Lima para avaliação',exact:true}).check();await page.getByRole('checkbox',{name:'Selecionar Marina Costa para avaliação',exact:true}).check();await page.getByRole('button',{name:'Preparar avaliação',exact:true}).click();await page.getByRole('heading',{name:'Avaliação do processo',exact:true}).waitFor();
  check(`${width}: configuration inherits two selected candidates without implicit writes`,(await calls(page)).every(c=>c.action==='load'));
  check(`${width}: defaults 20 questions / 60 minutes / easy / bank`,await page.getByRole('spinbutton',{name:'Quantidade de questões',exact:true}).inputValue()==='20'&&await page.getByRole('spinbutton',{name:'Duração em minutos',exact:true}).inputValue()==='60'&&(await page.locator('body').innerText()).includes('8 fáceis · 8 médias · 4 difíceis'));
  await page.screenshot({path:`${dir}/configuration-${width}.png`,fullPage:true});
  await page.getByRole('button',{name:'Montar avaliação',exact:true}).click();await page.getByText('Revisar avaliação',{exact:true}).waitFor();await page.getByText('20 de 20 questões',{exact:false}).waitFor();
  check(`${width}: complete bank skips AI confirmation`,await page.getByRole('dialog').count()===0&&(await calls(page)).filter(c=>['generate','send_batch'].includes(c.action)).length===0);
  check(`${width}: candidate selection carried to review`,await page.getByRole('checkbox').filter({visible:true}).count()>0&&await page.getByRole('button',{name:'Aprovar e enviar aos 2 candidatos',exact:true}).count()===1);
  await page.getByText('Questão 1 ·',{exact:false}).first().click();await page.getByRole('button',{name:'Editar questão',exact:true}).first().click();await page.getByRole('textbox',{name:'Enunciado',exact:true}).fill('Editada: questão sintética revisável');await page.getByRole('button',{name:'Salvar para revisão',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
  check(`${width}: changed content highlighted for review`,(await page.locator('body').innerText()).includes('Nova ou alterada · revisar'));
  await page.screenshot({path:`${dir}/review-${width}.png`,fullPage:true});
  check(`${width}: review no global horizontal overflow`,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  await page.getByRole('textbox',{name:'Prazo de acesso',exact:true}).fill('2026-12-10T12:00');await page.waitForTimeout(250);
  await page.evaluate(()=>window.__processFixture.fail=true);await page.getByRole('button',{name:'Aprovar e enviar aos 2 candidatos',exact:true}).click();await page.getByText('Falha sintética. O último estado confirmado foi preservado.',{exact:true}).waitFor();
  await page.waitForFunction(()=>document.querySelector('input[aria-label="Prazo de acesso"]')?.value?.startsWith('2026-12-10T12:00')&&!document.querySelector('.process-assessment .ant-btn-loading'));
  check(`${width}: failed send retains selected recipients and deadline`,await page.getByRole('button',{name:'Aprovar e enviar aos 2 candidatos',exact:true}).count()===1&&(await page.getByRole('textbox',{name:'Prazo de acesso',exact:true}).inputValue()).startsWith('2026-12-10T12:00'));
  await page.evaluate(()=>window.__processFixture.fail=false);await page.getByRole('button',{name:'Aprovar e enviar aos 2 candidatos',exact:true}).click();await page.getByText('2 convite(s) registrado(s).',{exact:false}).waitFor();
  const sends=(await calls(page)).filter(c=>c.action==='send_batch');check(`${width}: lost/failed response retry keeps batch id`,sends.length===2&&sends[0].body.requestId===sends[1].body.requestId);check(`${width}: batch only requested recipients`,sends[1].body.recipients.length===2);
  check(`${width}: first send freezes common proof and exposes individual states`,await page.getByText('Prova fixada no primeiro envio',{exact:true}).count()===1&&await page.getByRole('button',{name:'Editar questão',exact:true}).count()===0&&await page.getByText('Aplicações e resultados individuais',{exact:true}).count()===1);
  await page.screenshot({path:`${dir}/issued-${width}.png`,fullPage:true});
  await open(page,'partial');await page.getByRole('button',{name:'Montar avaliação',exact:true}).click();await page.getByRole('dialog').waitFor();check(`${width}: partial bank shows exact deficit`,await page.getByRole('button',{name:'Gerar 10 questões por IA',exact:true}).count()===1);
  await page.getByRole('button',{name:'Cancelar',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});check(`${width}: cancel performs zero AI/send and preserves bank draft`,!(await calls(page)).some(c=>['generate','send_batch'].includes(c.action))&&await page.evaluate(()=>window.__processFixture.workspace.assessment.questions.length)===10);
  await page.getByRole('button',{name:'Completar 10 questões por IA',exact:true}).click();await page.getByRole('button',{name:'Gerar 10 questões por IA',exact:true}).click();await page.getByText('Propostas de IA incorporadas.',{exact:false}).waitFor();
  const gen=(await calls(page)).filter(c=>c.action==='generate');check(`${width}: explicit AI generates only exact deficit`,gen.length===1&&gen[0].body.distribution.reduce((s,p)=>s+p.quantity,0)===10);check(`${width}: bank and generated proposals coexist with pending review`,await page.evaluate(()=>window.__processFixture.workspace.assessment.questions.filter(q=>q.source==='ai'&&q.review==='pending').length)===10);
  await page.screenshot({path:`${dir}/partial-ai-${width}.png`,fullPage:true});
  await open(page,'issued');await page.getByRole('button',{name:'Ver resultado e atividade',exact:true}).first().click();await page.getByRole('tab',{name:'Atividade por questão',exact:true}).click();await page.getByText('Mouse total / maior',{exact:true}).first().waitFor();check(`${width}: private individual activity retains method and limits`,await page.getByText('Mouse total / maior',{exact:true}).count()>=1&&(await page.getByRole('dialog').innerText()).includes('Não comprovam pesquisa'));
  await page.screenshot({path:`${dir}/activity-${width}.png`,fullPage:true});
  await open(page,'history');check(`${width}: historical process remains read-only`,await page.getByRole('button',{name:'Montar avaliação',exact:true}).count()===0&&await page.getByRole('button',{name:'Editar configuração',exact:true}).count()===0);
  await open(page,'reuse');await page.getByRole('combobox',{name:'Prova anterior compatível',exact:true}).click();await page.getByText('Acompanhamento anterior · 20 questões · 60 min',{exact:true}).click();await page.getByRole('button',{name:'Reutilizar prova',exact:true}).click();await page.getByText('20 de 20 questões',{exact:false}).waitFor();check(`${width}: reuse is explicit and excludes old applications`,(await calls(page)).filter(c=>c.action==='reuse').length===1&&await page.evaluate(()=>window.__processFixture.workspace.attempts.length)===0);
  check(`${width}: no runtime exceptions`,errors.length===0);check(`${width}: no external requests`,external.length===0);await page.close();
 }
}finally{await writeFile(`${dir}/checks.json`,JSON.stringify({checks,limits:['Real components, synthetic services; no production candidate/AI/email call.']},null,2));await browser.close();}
console.log(JSON.stringify({passed:checks.filter(c=>c.pass).length,total:checks.length}));
