import test from 'node:test';
import assert from 'node:assert/strict';
import {readProfileSynthesisResult,readProfileSynthesisView,PROFILE_SYNTHESIS_QUESTIONS} from '../../dist/src/domain/profileSynthesis.js';
import {providerRequest,generateSynthesis,runOnce} from '../../scripts/profile-synthesis-worker.mjs';
import {sources,result} from '../fixtures/profileSynthesis.mjs';
test('eight deep axes and grounded compact result',()=>{ assert.equal(PROFILE_SYNTHESIS_QUESTIONS.length,8); assert.deepEqual(readProfileSynthesisResult(result,sources),result); });
test('malformed Unicode rejected before PostgreSQL while valid Unicode preserved',()=>{const x=structuredClone(result);x.overview[0].text='Atuação \ud800';assert.throws(()=>readProfileSynthesisResult(x,sources));x.overview[0].text='Atuação financeira ✅';assert.equal(readProfileSynthesisResult(x,sources).overview[0].text,x.overview[0].text);});
for(const [name,mutate] of [
 ['missing field',x=>delete x.overview],['unknown source',x=>x.overview[0].sourceIds=['invented']],['reordered axis',x=>x.answers.reverse()],['extra field',x=>x.score=99],['invalid nature',x=>x.overview[0].nature='verified'],['null nature',x=>x.overview[0].nature=null],['duplicate reference',x=>x.overview[0].sourceIds.push(x.overview[0].sourceIds[0])],['too long',x=>x.overview[0].text='word '.repeat(121)],['partial without gap',x=>x.answers[0].missingInformation=[]],['insufficient with invention',x=>x.answers[0].status='insufficient'],['too many questions',x=>x.clarifications.push(...x.clarifications)],['unsupported verification',x=>x.overview[0].text='Competência verificada por Assessment.'],['control character',x=>x.overview[0].text='bad\u0000text']
])test(`reject ${name}`,()=>{const x=structuredClone(result);mutate(x);assert.throws(()=>readProfileSynthesisResult(x,sources));});
test('common read excludes body and preserves labeled prior result with its own references',()=>{const refs=sources.map(({text,...x})=>x);const raw={organizationId:'a',personId:'p',profileId:'v',profileVersion:1,state:'queued',analysisId:null,generatedAt:null,model:null,result:null,previous:{analysisId:'old',profileVersion:1,generatedAt:'2026-10-04T12:00:00Z',result,sources:refs},sources:refs,errorCode:null,basisHash:'a'.repeat(64)};assert.equal(readProfileSynthesisView(raw,'a','p').previous.analysisId,'old');assert.throws(()=>readProfileSynthesisView(raw,'b','p'));});
test('request uses stable strict schema without tools, identities or stored provider response',()=>{const r=providerRequest([{...sources[0],text:'Contato qa@example.invalid (11) 99999-0000'}],'gpt-5.6-luna');assert.equal(r.store,false);assert.equal(r.tools,undefined);assert.equal(r.text.format.strict,true);assert(!r.input[0].content[0].text.includes('qa@example.invalid'));assert(!r.input[0].content[0].text.includes('99999'));assert.throws(()=>providerRequest([{...sources[0],text:'x'.repeat(19000)}],'gpt-5.6-luna'));});
const config={supabaseUrl:'https://fixture.supabase.co',publishableKey:'public-key',workerSecret:'secret'.repeat(12),openaiKey:'private-key',model:'gpt-5.6-luna'};
const response={status:'completed',model:config.model,usage:{input_tokens:100,output_tokens:200},output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(result)}]}]};
test('provider parser accepts grounded output and rejects incomplete/refusal/unknown model',async()=>{assert.deepEqual((await generateSynthesis(sources,config,async()=>Response.json(response))).result,result);for(const raw of [{...response,status:'incomplete'},{...response,model:'unapproved'}, {...response,output:[{type:'message',content:[{type:'refusal'}]}]}])await assert.rejects(generateSynthesis(sources,config,async()=>Response.json(raw)));});
test('one claim, one call, one completion; no PII or secret in operational result',async()=>{const calls=[];const state=await runOnce(config,async(url,options)=>{calls.push({url,body:JSON.parse(options.body)});if(url.includes('claim_'))return Response.json({id:'job',lease:'lease',model:config.model,sources});if(url.includes('complete_'))return new Response(null,{status:204});return Response.json(response);});assert.equal(calls.length,3);assert.equal(state.state,'complete');assert(!JSON.stringify(state).includes('secret'));assert.equal(calls[2].body.p_result.contractVersion,result.contractVersion);});
test('empty queue makes zero provider calls; transient failure completed with fixed code',async()=>{let calls=0;assert.equal((await runOnce(config,async()=>{calls++;return Response.json(null);})).state,'idle');assert.equal(calls,1);const bodies=[];await runOnce(config,async(url,options)=>{if(url.includes('claim_'))return Response.json({id:'job',lease:'lease',model:config.model,sources});if(url.includes('complete_')){bodies.push(JSON.parse(options.body));return new Response(null,{status:204});}return new Response('private error content',{status:429});});assert.equal(bodies[0].p_error,'RATE_LIMITED');assert.equal(bodies[0].p_result,null);});
