import { useMemo } from "react";
import { createRoot } from "react-dom/client";
import { Alert, Button, ConfigProvider, Input } from "antd";
import ptBR from "antd/locale/pt_BR";
import { PersonProfessionalEvidenceMap } from "../../../web/src/components/profile/PersonProfessionalEvidenceMap";
import { CanonicalProfileHeader } from "../../../web/src/components/profile/CanonicalProfileView";
import { m72Fixture } from "../../fixtures/m72PersonEvidence";
import type { CompetencyCurationAdapter } from "../../../web/src/domain/profileCompetencyCuration";
import type { PrismaProfileView } from "../../../web/src/domain/canonicalProfile";
import { focusNoticeFields } from "../../../web/src/ui/noticeActions";
import { actionableMessageError } from "../../../web/src/ui/ActionableMessage";
import { prismaTheme } from "../../../web/src/ui/theme";
import "../../../web/src/styles.css";
import "../../../web/src/ui/foundation.css";
const scenario = new URLSearchParams(location.search).get("case") ?? "save";
const initial=m72Fixture();initial.associations=initial.associations.filter((x)=>x.nature==="declared").slice(0,1);
initial.associations[0]!.concept={...initial.associations[0]!.concept,scope:scenario==="global"?"global":"organization",label:"Transformação operacional",classificationState:"pending",classification:null};
const second=structuredClone(initial.associations[0]!);second.id="linked-second";initial.associations.push(second);
const subgroup={id:"synthetic-group",code:"H1",label:"Gestão, Negócios e Estratégia",scope:"global" as const,organizationId:null,macroGroupCode:"hard" as const,definition:"Gestão de processos e operações."};
const profile:PrismaProfileView={identity:{fullName:"Ana Ribeiro",professionalTitle:"Gestora de operações",location:"São Paulo, SP",lifecycleLabel:"Perfil vigente",operationalStatusLabel:"Ativo"},about:null,experiences:[],education:[],competencyGroups:[],credentials:{certifications:[],languages:[]},customSections:[],version:{profileId:initial.profile.id,number:1,publishedAt:initial.profile.publishedAt,current:true}};
let calls:Parameters<CompetencyCurationAdapter["classify"]>[0][]=[];let loads=0;
function Harness(){const adapter=useMemo<CompetencyCurationAdapter>(()=>({canUseGlobal:false,async loadSubgroups(){loads++;return[subgroup];},async search(){return[];},async suggestDescription(){return"";},async save(){return{projection:initial,outcome:"alias"};},async refresh(){return initial;},async loadEvidenceSources(){return[];},async linkEvidence(){return initial;},async classify(input){calls.push(input);await new Promise((r)=>setTimeout(r,100));if(scenario==="error")throw Error("O grupo escolhido não está mais disponível. Atualize as opções e escolha um grupo ativo.");const next=structuredClone(initial);for(const association of next.associations)association.concept={...association.concept,classificationState:"classified",classification:{macroGroupCode:"hard",macroGroupLabel:"Hard Skills",subgroupId:subgroup.id,subgroupCode:"H1",subgroupLabel:subgroup.label,classificationVersion:1,taxonomyVersion:"competency-taxonomy-2.0.0"}};return next;}}),[]);
return <ConfigProvider locale={ptBR} theme={prismaTheme}><div className="prisma-page prisma-profile-page"><CanonicalProfileHeader profile={profile}/>{scenario==="focus"?<><Alert type="error" title="Corrija o telefone antes de salvar." action={<Button onClick={(event)=>focusNoticeFields(event.currentTarget)}>Ir para a correção</Button>}/><Input id="untouched" defaultValue="Rascunho preservado"/><div style={{height:1200}}/><label htmlFor="invalid-phone">Telefone</label><Input id="invalid-phone" aria-invalid="true" defaultValue="telefone incompleto"/><Button onClick={()=>actionableMessageError("A resposta não foi confirmada. Consulte o campo antes de repetir.",{label:"Conferir telefone",onClick:()=>document.getElementById("invalid-phone")?.focus()})}>Abrir aviso temporário</Button></>:<PersonProfessionalEvidenceMap profile={profile} projection={initial} projectionError={null} curation={scenario==="readonly"?undefined:adapter} onOpenSource={()=>undefined}/>}</div></ConfigProvider>;}
createRoot(document.getElementById("app")!).render(<Harness/>);
const pause=(ms=200)=>new Promise((r)=>setTimeout(r,ms));
const button=(text:string)=>[...document.querySelectorAll<HTMLButtonElement>("button")].find((x)=>x.textContent===text);
declare global{interface Window{__QA_NOTICE_DONE?:boolean;__QA_NOTICE_REPORT?:unknown;}}
setTimeout(async()=>{const checks:Record<string,boolean>={};try{
if(scenario==="focus") {button("Ir para a correção")?.click();await pause();checks.correctInvalidField=document.activeElement?.id==="invalid-phone";checks.draftPreserved=(document.getElementById("untouched") as HTMLInputElement).value==="Rascunho preservado";button("Abrir aviso temporário")?.click();await pause();checks.actionableToast=Boolean(button("Conferir telefone"));button("Conferir telefone")?.click();checks.toastActionTarget=document.activeElement?.id==="invalid-phone";}
else {button("Competências")?.click();await pause();checks.problemExplained=document.body.textContent!.includes("Vincular evidências não define esse grupo");checks.linkCountVisible=document.body.textContent!.includes("2 evidências vinculadas");button(["global","readonly"].includes(scenario)?"Ver orientação":"Definir grupo")?.click();await pause();checks.correctConceptDialog=document.body.textContent!.includes("Definir grupo de Transformação operacional");
if(["global","readonly"].includes(scenario)){checks.noAuthorityNoMutation=!button("Salvar grupo")&&calls.length===0&&loads===0;checks.readOnlyExplanation=document.body.textContent!.includes("só pode ser definido por um administrador");}
else{checks.noPreselection=Boolean(button("Salvar grupo")?.disabled)&&document.querySelectorAll(".ant-modal .ant-select-content-has-value").length===0;button("Escolher grupo")?.click();await pause();checks.focusCorrectGroup=document.activeElement?.id==="prisma-competency-group";document.querySelector<HTMLElement>(".ant-modal .ant-select-content")?.dispatchEvent(new MouseEvent("mousedown",{bubbles:true}));await pause();[...document.querySelectorAll<HTMLElement>(".ant-select-item-option")].find((x)=>x.textContent===subgroup.label)?.click();await pause();checks.humanChoiceEnablesSave=Boolean(button("Salvar grupo")&&!button("Salvar grupo")?.disabled);document.dispatchEvent(new MouseEvent("mousedown",{bubbles:true}));document.body.dataset.qaCapture="ready";for(let i=0;i<50&&document.body.dataset.qaCapture==="ready";i++)await pause(100);button("Salvar grupo")?.click();button("Salvar grupo")?.click();await pause(400);checks.oneCall=calls.length===1&&calls[0]?.conceptId===initial.associations[0]!.concept.id&&calls[0]?.subgroupId===subgroup.id;
if(scenario==="error"){checks.errorKeepsChoice=Boolean(document.querySelector(".ant-modal"))&&document.body.textContent!.includes("Atualizar opções")&&Boolean(document.querySelector(".ant-modal .ant-select-content-has-value"));button("Atualizar opções")?.click();await pause();checks.reloadGroupsPreservesChoice=loads===2&&Boolean(document.querySelector(".ant-modal .ant-select-content-has-value"));}
else {checks.pendingRemoved=!document.body.textContent!.includes("Grupo ainda não definido");checks.classifiedGroupVisible=document.body.textContent!.includes(subgroup.label);document.querySelector<HTMLElement>(".ant-collapse-header")?.click();await pause();checks.evidencePreserved=document.body.textContent!.includes("2 evidências");}}
}
checks.noHorizontalOverflow=document.documentElement.scrollWidth<=innerWidth+1;
}catch(e){checks.unexpected=false;}window.__QA_NOTICE_REPORT={scenario,width:innerWidth,checks,pass:Object.values(checks).every(Boolean)};window.__QA_NOTICE_DONE=true;},600);
