function assert(v:unknown,m:string){if(!v)throw Error(m);}
for(const[k,v]of Object.entries({SUPABASE_URL:'https://fixture.supabase.co',SUPABASE_ANON_KEY:'public-fixture',SUPABASE_SERVICE_ROLE_KEY:'backend-fixture',OPENAI_API_KEY:'provider-fixture'}))Deno.env.set(k,v);
let handler:(r:Request)=>Promise<Response>;const serve=Deno.serve,originalFetch=fetch;Deno.serve=((h:typeof handler)=>{handler=h;return {} as ReturnType<typeof Deno.serve>;})as typeof Deno.serve;await import('./index.ts');Deno.serve=serve;
const org='23000000-0000-4000-8000-000000000001',id='23000000-0000-4000-8000-000000000002',requestId='23000000-0000-4000-8000-000000000003',req='23000000-0000-4000-8000-000000000004';
Deno.test('oversized input and unsupported origins stop before any backend or provider call',async()=>{
 try{globalThis.fetch=()=>{throw Error('backend must not be called');};
 const oversized=await handler(new Request('https://fixture.invalid/assessment',{method:'POST',headers:{Origin:'http://127.0.0.1:5555'},body:'x'.repeat(256*1024+1)}));assert(oversized.status===422,'oversized stream rejected');
 const foreign=await handler(new Request('https://fixture.invalid/assessment',{method:'POST',headers:{Origin:'https://foreign.invalid'},body:'{}'}));assert(foreign.status===403,'foreign origin denied');
 }finally{globalThis.fetch=originalFetch;}
});
Deno.test('explicit assessment generation uses minimized requirements, records cost and persists pending human proposals; invalid output records failure',async()=>{
try{for(const valid of [true,false]){const calls:Array<{url:string;body:any}>=[];
 globalThis.fetch=async(input,init)=>{const url=String(input),body=typeof init?.body==='string'?JSON.parse(init.body):{};calls.push({url,body});
 if(url.includes('/auth/v1/user'))return Response.json({id,role:'authenticated'});
 if(url.endsWith('/position_assessment_generation_request'))return Response.json({actor_id:id,revision:1,requirements:[{id:req,label:'APIs REST',competencyKey:'APIs REST'}],distribution:[{requirementId:req,difficulty:'easy',quantity:1}],status:'reserved'});
 if(url.endsWith('/record_ai_history_v1'))return Response.json(body.p_action==='open_request'?{request:{id:requestId}}:{acquired:true});
 if(url==='https://api.openai.com/v1/responses'){assert(calls.some(c=>c.body.p_action==='begin_attempt'),'usage acquired before provider');assert(body.model==='gpt-5.6-luna'&&body.store===false&&!body.tools,'approved provider contract');assert(!body.input.includes('organizationId')&&!body.input.includes('personId'),'no identity');return Response.json({status:valid?'completed':'incomplete',model:'gpt-5.6-luna',usage:{input_tokens:100,output_tokens:200},output:[{type:'message',content:[{type:'output_text',text:JSON.stringify({items:[{requirementId:req,competencyKey:'APIs REST',difficulty:'easy',stem:'Qual código indica criação?',options:['A','B','C','D','E'].map((id,i)=>({id,label:String(201+i)})),correctOptionId:'A',explanation:'HTTP 201 indica recurso criado.'}]})}]}]});}
 return Response.json({status:body.p_success?'succeeded':'failed'});
 };
 const response=await handler(new Request('https://fixture.invalid/assessment',{method:'POST',headers:{Origin:'http://127.0.0.1:5555',Authorization:'Bearer fixture','Content-Type':'application/json'},body:JSON.stringify({contract:'position-assessment-1.0.0',action:'generate',organizationId:org,assessmentId:id,requestId,distribution:[{requirementId:req,difficulty:'easy',quantity:1}]})}));assert(response.status===(valid?200:422),'validity enforced');
 const finish=calls.find(c=>c.url.endsWith('/position_assessment_generation_finish'))!.body;assert(finish.p_success===valid,'backend proposal completion');if(valid)assert(finish.p_questions[0].review==='pending'&&!finish.p_questions[0].approvedBy,'human review never automated');const history=calls.filter(c=>c.url.endsWith('/record_ai_history_v1'));assert(history[2].body.p_data.inputTokens===100&&history[2].body.p_data.outputTokens===200,'observed usage');assert(history[3].body.p_data.status===(valid?'succeeded':'failed'),'failed output keeps incurred cost');assert(!JSON.stringify(history).includes('APIs REST'),'metadata only');
}}finally{globalThis.fetch=originalFetch;}
});
Deno.test('human email action persists claim before transport, personal token stays in fragment and escaped email; backend receipt is confirmed',async()=>{
 const calls:Array<{url:string;body:any}>=[];try{globalThis.fetch=async(input,init)=>{const url=String(input),body=typeof init?.body==='string'?JSON.parse(init.body):{};calls.push({url,body});if(url.includes('/auth/v1/user'))return Response.json({id,role:'authenticated'});if(url.endsWith('/position_assessment_invite'))return Response.json({deliveryId:id,attemptId:req,state:'queued'});if(url.endsWith('/position_assessment_email_configuration'))return Response.json('re_synthetic_not_a_real_key');if(url.endsWith('/position_assessment_delivery'))return Response.json(body.p_action==='claim'?{acquired:true,leaseId:req,id,organizationId:org,firstAttemptAtMs:Date.now(),expiresAtMs:Date.now()+86400000,recipient:'fixture@example.invalid',subject:'Convite',message:'<script>fixture</script>',token:'a'.repeat(64)}:{state:'sent'});if(url==='https://api.resend.com/emails'){assert(calls.some(c=>c.body.p_action==='claim'),'first attempt persisted');assert(body.html.includes('&lt;script&gt;')&&!body.html.includes('<script>'),'escaped body');assert(body.html.includes('/assessment/#'+ 'a'.repeat(64)),'token never enters HTTP request path');return Response.json({id:req});}throw Error('unexpected destination');};
 const response=await handler(new Request('https://fixture.invalid/assessment',{method:'POST',headers:{Origin:'http://127.0.0.1:5555',Authorization:'Bearer fixture','Content-Type':'application/json'},body:JSON.stringify({contract:'position-assessment-1.0.0',action:'send',organizationId:org,assessmentId:id,requestId,recipient:'fixture@example.invalid',subject:'Convite',message:'<script>fixture</script>',expiresAt:new Date(Date.now()+86400000).toISOString()})}));const out=await response.json();assert(response.status===200&&out.state==='sent','receipt success');assert(!JSON.stringify(out).includes('a'.repeat(64)),'raw token not returned to operator');assert(calls.at(-1)?.body.p_payload.providerEmailId===req,'acceptance persisted');
 }finally{globalThis.fetch=originalFetch;}
});
Deno.test('shared batch uses authenticated atomic queue only, preserves receipts and rejects portal contract confusion',async()=>{
 const calls:string[]=[];try{globalThis.fetch=async(input,init)=>{const url=String(input);calls.push(url);if(url.includes('/auth/v1/user'))return Response.json({id,role:'authenticated'});if(url.endsWith('/process_assessment_issue')){const body=JSON.parse(String(init?.body));assert(body.p_revision===4&&body.p_recipients.length===2,'revision and complete recipient batch preserved');return Response.json({status:'queued',receipts:[{personId:req,deliveryId:id,state:'queued'}]});}throw Error('provider or unrelated boundary must not be called');};
 const request=(contract:string,action:string)=>new Request('https://fixture.invalid/assessment',{method:'POST',headers:{Origin:'http://127.0.0.1:5555',Authorization:'Bearer fixture','Content-Type':'application/json'},body:JSON.stringify({contract,action,organizationId:org,assessmentId:id,revision:4,requestId,recipients:[{personId:id,email:'a@example.invalid'},{personId:req,email:'b@example.invalid'}],subject:'Convite',message:'Instruções',expiresAt:'2099-01-01T00:00:00Z'})});
 const response=await handler(request('process-assessment-1.0.0','send_batch')),out=await response.json();assert(response.status===200&&out.status==='queued'&&!JSON.stringify(out).includes('token'),'queue receipt only');assert(calls.length===2,'no synchronous provider call');
 calls.length=0;assert((await handler(request('process-assessment-1.0.0','start'))).status===400,'operator envelope cannot access portal');assert((await handler(request('position-assessment-1.0.0','send_batch'))).status===409,'batch requires its operator contract');assert(calls.length===0,'contract rejection precedes IO');
 }finally{globalThis.fetch=originalFetch;}
});
