function assert(v:unknown,m:string){if(!v)throw Error(m);}
for(const[k,v]of Object.entries({SUPABASE_URL:'https://fixture.supabase.co',SUPABASE_ANON_KEY:'public-fixture',SUPABASE_SERVICE_ROLE_KEY:'backend-fixture',OPENAI_API_KEY:'provider-fixture',M51C_AI_ITEM_GENERATION_ENABLED:'true',M51C_GENERATION_MODEL:'gpt-5.6-luna',M51C_ESTIMATED_COST_CENTS_PER_ITEM:'1',M51C_INPUT_COST_CENTS_PER_MILLION:'20',M51C_OUTPUT_COST_CENTS_PER_MILLION:'120'}))Deno.env.set(k,v);
let handler:(r:Request)=>Promise<Response>;const serve=Deno.serve,originalFetch=fetch;Deno.serve=((h:typeof handler)=>{handler=h;return {} as ReturnType<typeof Deno.serve>;})as typeof Deno.serve;await import('./index.ts');Deno.serve=serve;
const org='23000000-0000-4000-8000-000000000001',id='23000000-0000-4000-8000-000000000002';
Deno.test('legacy item generation remains gated and records actual attempts without enabling legacy production policy',async()=>{
 const calls:Array<{url:string;body:any}>=[];try{globalThis.fetch=async(input,init)=>{const url=String(input),body=typeof init?.body==='string'?JSON.parse(init.body):{};calls.push({url,body});if(url.includes('/auth/v1/user'))return Response.json({id,role:'authenticated'});if(url.endsWith('/request_m51c_item_generation'))return Response.json({requestId:id,status:'queued',replayed:false});if(url.includes('/assessment_item_generation_requests'))return Response.json({id,organization_id:org,generation_need_id:id,model:'gpt-5.6-luna',prompt_version:'fixture-1.0.0',directives:{}});if(url.includes('/assessment_item_generation_needs'))return Response.json({competency_key:'JavaScript',target_level:'intermediate',dimension:'knowledge',modality:'multiple_choice',language:'pt-BR'});if(url.endsWith('/record_ai_history_v1'))return Response.json(body.p_action==='open_request'?{request:{id}}:{acquired:true});if(url==='https://api.openai.com/v1/responses'){assert(calls.some(c=>c.body.p_action==='begin_attempt'),'ledger before provider');return Response.json({id:'fixture-provider',usage:{input_tokens:10,output_tokens:20},output:[{content:[{type:'output_text',text:'{"items":[]}'}]}]});}return Response.json({status:'failed'});};
 const response=await handler(new Request('https://fixture.invalid/generation',{method:'POST',headers:{Origin:'http://127.0.0.1:5555',Authorization:'Bearer fixture','Content-Type':'application/json'},body:JSON.stringify({schemaVersion:'m51c-assessment-item-generation-request-1.0.0',organizationId:org,generationNeedId:id,quantity:1,targetScope:'organization',idempotencyKey:'fixture-generation-key'} )}));assert(response.status===502,'legacy malformed quantity rejected');const history=calls.filter(c=>c.url.endsWith('/record_ai_history_v1'));assert(history.length===4,'logical and attempt history recorded');assert(history[2].body.p_data.inputTokens===10&&history[3].body.p_data.status==='failed','incurred usage preserved on validation failure');assert(!JSON.stringify(history).includes('JavaScript'),'no question payload stored in ledger');
 }finally{globalThis.fetch=originalFetch;}
});
