import {useEffect,useRef,useState} from "react";
import {Alert,Button,Checkbox,Modal,Radio,Skeleton,Tag} from "antd";
import {QuestionFocusTracker,type QuestionObservationScope} from "../../../src/domain/positionAssessment";
import {QuestionMouseTracker,MOUSE_SAMPLE_INTERVAL_MS} from "../../../src/domain/positionAssessmentActivity";
import type {ParticipantAssessment} from "../domain/positionAssessmentData";
import {positionAssessmentService as service} from "../infrastructure/supabase/positionAssessmentService";
import {PrismaCard} from "../ui/PrismaCard";
import "./positionAssessment.css";
type Event={eventId:string;questionInstanceId:string;questionVersion:string;kind:string;clientAtMs:number;sequence:number;method:string;values:Record<string,unknown>};
export function PositionAssessmentPortal({token}:{token:string}){
 const [data,setData]=useState<ParticipantAssessment|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[index,setIndex]=useState(0),[answers,setAnswers]=useState<Record<string,string>>({}),[marked,setMarked]=useState<string[]>([]),[sync,setSync]=useState("Carregando…"),[remaining,setRemaining]=useState<number|null>(null),[review,setReview]=useState(false);
 const savePending=useRef<Promise<void>|null>(null),loadSequence=useRef(0);
 const current=useRef<ParticipantAssessment|null>(null),draft=useRef({answers:{} as Record<string,string>,marked:[] as string[]}),dirty=useRef(false),saving=useRef(false),submitLock=useRef(false),events=useRef<Event[]>([]),sequence=useRef(0),eventLock=useRef(false),storageKey=useRef(""),scope=useRef<QuestionObservationScope|null>(null);
 const focus=useRef(new QuestionFocusTracker()),mouse=useRef(new QuestionMouseTracker()),visited=useRef(new Set<string>()),clockBase=useRef(Date.now()-performance.now());
 const at=()=>clockBase.current+performance.now();
 function persist(){try{if(storageKey.current)localStorage.setItem(storageKey.current,JSON.stringify({draft:draft.current,dirty:dirty.current,events:events.current,sequence:sequence.current}));}catch{setSync("Armazenamento local indisponível; mantenha a página aberta para sincronizar.");}}
 function queue(kind:string,method:string,values:Record<string,unknown>,s=scope.current){if(!s)return;events.current.push({eventId:crypto.randomUUID(),questionInstanceId:s.questionInstanceId,questionVersion:s.questionVersion,kind,clientAtMs:at(),sequence:sequence.current++,method,values});persist();}
 function observations(rows:unknown[]){for(const raw of rows){const value=raw as Record<string,unknown>,{organizationId,attemptId,questionInstanceId,questionVersion,kind,method,startedAtClientMs,endedAtClientMs,...values}=value;
  if(kind==="focus_episode"){values.startedAtClientMs=startedAtClientMs;values.endedAtClientMs=endedAtClientMs;}
  queue(kind as string,method as string,values,{organizationId:organizationId as string,attemptId:attemptId as string,questionInstanceId:questionInstanceId as string,questionVersion:questionVersion as string});}}
 async function flushEvents(){if(eventLock.current||!events.current.length||!["started","submitted"].includes(current.current?.status??""))return;eventLock.current=true;const batch=events.current.slice(0,100);try{await service.participant(token,"events",{events:batch});const ids=new Set(batch.map(e=>e.eventId));events.current=events.current.filter(e=>!ids.has(e.eventId));persist();if(!events.current.length&&current.current?.status==="submitted"){try{localStorage.removeItem(storageKey.current);}catch{/* server receipt is retained */}}}catch{setSync("Respostas preservadas; alguns sinais de atividade aguardam sincronização.");}finally{eventLock.current=false;}}
 async function save(){if(savePending.current)return savePending.current;if(!dirty.current||current.current?.status!=="started")return;const revision=current.current.revision;const operation=async()=>{saving.current=true;setSync("Salvando respostas…");const sent=structuredClone(draft.current);try{const confirmed=await service.participant(token,"save",{revision,...sent});current.current=confirmed;setData(confirmed);if(JSON.stringify(sent)===JSON.stringify(draft.current)){dirty.current=false;setSync("Respostas sincronizadas");}else setSync("Salvando novas alterações…");persist();}catch{setError("Não foi possível sincronizar. Suas respostas foram preservadas. Retome a sincronização antes de enviar.");setSync("Respostas locais preservadas · sincronização pendente");}finally{saving.current=false;}};savePending.current=operation();try{await savePending.current;}finally{savePending.current=null;}}
 async function load(){const revision=++loadSequence.current;setLoading(true);setError(null);try{const value=await service.participant(token,"load");if(revision!==loadSequence.current)return;current.current=value;setData(value);
  if(value.attemptId||value.receiptId){storageKey.current=`prisma-pa-buffer:${value.attemptId??value.receiptId}`;let saved:any=null;try{saved=JSON.parse(localStorage.getItem(storageKey.current)??"null");}catch{/* recover from server */}
   draft.current=saved?.dirty&&saved.draft?{answers:{...value.answers,...saved.draft.answers},marked:saved.draft.marked??value.marked??[]}:{answers:value.answers??{},marked:value.marked??[]};dirty.current=value.status!=="submitted"&&!!saved?.dirty;events.current=Array.isArray(saved?.events)?saved.events:[];sequence.current=Number.isSafeInteger(saved?.sequence)?saved.sequence:0;setAnswers(draft.current.answers);setMarked(draft.current.marked);setSync(dirty.current?"Respostas locais recuperadas · sincronização pendente":"Respostas sincronizadas");
  }else setSync("Comprovante confirmado");
 }catch{setError("Convite indisponível, expirado ou acesso interrompido. Confira o link pessoal e tente novamente; as respostas locais foram preservadas.");}finally{setLoading(false);}}
 useEffect(()=>{void load();const timer=setInterval(()=>{void save();void flushEvents();const deadline=current.current?.deadline;setRemaining(deadline?Math.max(0,Math.ceil((Date.parse(deadline)-Date.now())/1000)):null);},1000);return()=>clearInterval(timer);},[token]);
 const q=data?.questions?.[index];
 useEffect(()=>{if(!data?.attemptId||!data.organizationId||data.status!=="started"||!q)return;const s={organizationId:data.organizationId,attemptId:data.attemptId,questionInstanceId:q.id,questionVersion:q.version};const time=at();scope.current=s;
  observations(focus.current.activate(s,time));observations(focus.current.observe({hidden:document.hidden,focused:document.hasFocus()},time));observations(mouse.current.activate(s,time,{active:!document.hidden&&document.hasFocus(),previouslyAnswered:!!draft.current.answers[q.id]}));
  if(visited.current.has(q.id))queue("question_reopened","position-assessment-browser-signals-1.0.0",{support:"observed",limitation:"no_intent_inference"},s);visited.current.add(q.id);
  return()=>{const time=at();observations(focus.current.activate(null,time));observations(mouse.current.activate(null,time,{active:false,previouslyAnswered:true}));scope.current=null;};
 },[data?.attemptId,data?.status,q?.id]);
 useEffect(()=>{const active=()=>{const time=at();observations(focus.current.observe({hidden:document.hidden,focused:document.hasFocus()},time));mouse.current.setActive(!document.hidden&&document.hasFocus(),time);};
  const move=(e:PointerEvent)=>{if(e.pointerType==="mouse")mouse.current.movement(at());};
  let scale=window.visualViewport?.scale??null;
  const zoom=()=>{const next=window.visualViewport?.scale??null;if(scale!==null&&next!==null&&next!==scale){queue("zoom_observed","position-assessment-browser-signals-1.0.0",{previousScale:scale,scale:next,support:"visual_viewport",limitation:"page_zoom_and_monitor_scale_not_observable"});scale=next;}};
  const capture=(e:KeyboardEvent)=>{const shortcut=e.code==="PrintScreen"?"PrintScreen":e.metaKey&&e.shiftKey&&["Digit3","Digit4","Digit5"].includes(e.code)?`Meta+Shift+${e.code}`:e.metaKey&&e.shiftKey&&e.code==="KeyS"?"Meta+Shift+KeyS":null;if(shortcut)queue("capture_shortcut_observed","position-assessment-browser-signals-1.0.0",{shortcut,support:"received_shortcut",limitation:"capture_success_and_other_methods_not_observable"});};
  window.addEventListener("blur",active);window.addEventListener("focus",active);document.addEventListener("visibilitychange",active);window.addEventListener("pointermove",move);window.addEventListener("keydown",capture);window.visualViewport?.addEventListener("resize",zoom);
  const timer=setInterval(()=>mouse.current.sample(at()),MOUSE_SAMPLE_INTERVAL_MS);
  const leave=()=>{persist();};window.addEventListener("pagehide",leave);
  return()=>{clearInterval(timer);window.removeEventListener("blur",active);window.removeEventListener("focus",active);document.removeEventListener("visibilitychange",active);window.removeEventListener("pointermove",move);window.removeEventListener("keydown",capture);window.visualViewport?.removeEventListener("resize",zoom);window.removeEventListener("pagehide",leave);};
 },[token]);
 function choose(option:string){if(!q||submitLock.current)return;if(draft.current.answers[q.id]&&draft.current.answers[q.id]!==option)queue("answer_changed","position-assessment-browser-signals-1.0.0",{support:"observed",limitation:"no_intent_inference"});observations(mouse.current.firstChoice(at()));draft.current={...draft.current,answers:{...draft.current.answers,[q.id]:option}};dirty.current=true;setAnswers(draft.current.answers);setSync("Resposta preservada · salvando…");persist();void save();}
 async function submit(){if(submitLock.current)return;submitLock.current=true;setBusy(true);try{await save();if(dirty.current)throw Error("Confirme a sincronização das respostas antes de enviar.");observations(focus.current.activate(null,at()));observations(mouse.current.activate(null,at(),{active:false,previouslyAnswered:true}));await flushEvents();const result=await service.participant(token,"submit",{revision:current.current?.revision,...draft.current});current.current=result;setData(result);dirty.current=false;persist();if(!events.current.length){try{localStorage.removeItem(storageKey.current);}catch{/* receipt remains on server */}}else void flushEvents();setError(null);}catch(e){setError(e instanceof Error?e.message:"Envio não confirmado. Consulte o estado antes de tentar novamente.");}finally{submitLock.current=false;setBusy(false);}}
 if(loading&&!data)return <main className="pa-portal"><Skeleton active paragraph={{rows:10}} />{error?<Alert type="error" title={error} />:null}</main>;
 if(!data)return <main className="pa-portal"><Alert type="error" title={error??"Convite indisponível."} /><Button loading={loading} onClick={()=>void load()}>Tentar novamente</Button></main>;
 if(data.status==="submitted")return <main className="pa-portal"><PrismaCard title="Avaliação enviada"><p>Suas respostas foram recebidas e a avaliação foi concluída.</p><p>Comprovante: {data.receiptId}</p><p>{data.submittedAt?new Date(data.submittedAt).toLocaleString("pt-BR"):""}</p><p>A empresa responsável avaliará os próximos passos.</p></PrismaCard></main>;
 return <main className="pa-portal"><header><strong>PRISMA</strong><div><h1>{data.positionTitle}</h1><p>{data.personName} · Avaliação para Posição</p></div><Tag>{remaining!==null?`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,"0")} restantes`:`${data.durationMinutes} minutos`}</Tag></header>{error?<Alert type="error" showIcon title={error} action={<Button loading={loading} onClick={()=>void load()}>Retomar sincronização</Button>} />:null}
 {data.status==="invited"?<PrismaCard title="Antes de começar"><p>Você terá {data.durationMinutes} minutos a partir do início, respeitando o prazo de acesso: {data.expiresAt?new Date(data.expiresAt).toLocaleString("pt-BR"):""}.</p><p>Uma questão por vez, cinco alternativas e uma resposta por questão. Você pode navegar, marcar para revisão e retomar a mesma tentativa até o prazo. Confira suas respostas antes da confirmação final.</p><p>Responda com seus conhecimentos e mantenha esta janela ativa. Os sinais de atividade exibidos na seção abaixo são parciais e não comprovam pesquisa ou fraude.</p><details open><summary>Limites da observação</summary><p>São registrados episódios de foco, mouse parado antes da primeira escolha, alterações observáveis de escala e atalhos de captura recebidos pelo navegador. Nenhuma imagem, clipboard, histórico geral de teclas ou destino de outras janelas é coletado. Outros aparelhos, programas de captura e algumas alterações de zoom não são observáveis. Teclado, touch e acessibilidade podem produzir ausência de sinais de mouse; isso não é um resultado negativo.</p></details><Button type="primary" loading={busy} onClick={async()=>{setBusy(true);try{const value=await service.participant(token,"start");current.current=value;setData(value);setError(null);}catch{setError("Não foi possível iniciar; tente novamente.");}finally{setBusy(false);}}}>Li as instruções · iniciar avaliação</Button></PrismaCard>:<div className="pa-portal-body"><aside><details open><summary>Navegação das questões</summary><div className="pa-numbers">{data.questions?.map((q,n)=><button key={q.id} className={`pa-number${index===n?" current":""}${answers[q.id]?" answered":""}${marked.includes(q.id)?" marked":""}`} aria-label={`Questão ${n+1}${answers[q.id]?", respondida":""}${marked.includes(q.id)?", marcada para revisão":""}`} onClick={()=>{setIndex(n);setReview(false);}}>{n+1}</button>)}</div></details><p>Verde: respondida · borda amarela: revisar</p></aside><section className="pa-question"><Alert type="info" showIcon title="Responda com seus conhecimentos e mantenha esta janela ativa." description="Observações de foco, mouse, zoom e atalhos são parciais. Não há captura de imagens da sua tela." /><PrismaCard title={review?"Revisar antes de enviar":`Questão ${index+1} de ${data.questions?.length}`}>
 {review?<>{data.questions?.map((question,n)=><p key={question.id}><Button type="link" onClick={()=>{setIndex(n);setReview(false);}}>Questão {n+1}</Button>{answers[question.id]?`Resposta ${answers[question.id]}`:"Sem resposta"}{marked.includes(question.id)?" · marcada para revisão":""}</p>)}<Button type="primary" loading={busy} disabled={Object.keys(answers).length!==data.questions?.length||remaining===0} onClick={()=>Modal.confirm({title:"Enviar avaliação definitivamente?",content:"Após confirmar, as respostas não poderão ser alteradas.",okText:"Confirmar envio",cancelText:"Voltar à revisão",onOk:submit})}>Confirmar envio da avaliação</Button></>:q?<><h2>{q.stem}</h2><Radio.Group value={answers[q.id]??null} disabled={busy||remaining===0} onChange={e=>choose(String(e.target.value))}>{q.options.map(o=><Radio key={o.id} value={o.id}>{o.id} · {o.label}</Radio>)}</Radio.Group><Checkbox checked={marked.includes(q.id)} onChange={e=>{draft.current={...draft.current,marked:e.target.checked?[...new Set([...draft.current.marked,q.id])]:draft.current.marked.filter(id=>id!==q.id)};dirty.current=true;setMarked(draft.current.marked);persist();}}>Marcar para revisar</Checkbox><footer><Button disabled={index===0} onClick={()=>setIndex(n=>n-1)}>Anterior</Button><Button disabled={index>=(data.questions?.length??0)-1} onClick={()=>setIndex(n=>n+1)}>Próxima</Button><Button onClick={()=>setReview(true)}>Revisar e enviar</Button></footer></>:null}<div role="status" className="pa-sync">{sync} · {Object.keys(answers).length} de {data.questions?.length} respondidas</div>{remaining===0?<Alert type="warning" title="O prazo terminou. As respostas já sincronizadas foram preservadas; contate a empresa responsável." />:null}</PrismaCard></section><aside><PrismaCard title="Informações"><p>Suas respostas são salvas durante o preenchimento. Aguarde a confirmação antes de fechar a página.</p><p>Os sinais são parciais e não comprovam pesquisa ou fraude. Recursos de acessibilidade podem modificar esses sinais.</p><Button onClick={()=>void save()}>Sincronizar agora</Button></PrismaCard></aside></div>}</main>;
}
