import {useEffect,useRef,useState} from 'react';
import {Alert,Button,Checkbox,Collapse,Empty,Input,InputNumber,Modal,Radio,Select,Skeleton,Space,Table,Tag} from 'antd';
import {CheckSquareFilled,HistoryOutlined,InfoCircleOutlined,ReloadOutlined,SettingOutlined} from '@ant-design/icons';
import {assembleProcessAssessment,processAssessmentDeficit,splitGenerationParts} from '../../../src/domain/processAssessment';
import {createDistributionSnapshot,inspectComposition} from '../../../src/domain/positionAssessment';
import type {AssessmentAttempt,AssessmentQuestion,PositionAssessment} from '../domain/positionAssessmentData';
import type {ProcessAssessmentWorkspace} from '../domain/processAssessmentData';
import type {OrganizationMembership} from '../shared/access';
import {processAssessmentService as service} from '../infrastructure/supabase/processAssessmentService';
import {positionAssessmentService} from '../infrastructure/supabase/positionAssessmentService';
import {AssessmentAttemptResults,assessmentStateLabels as states} from '../components/AssessmentAttemptResults';
import {PrismaPage,PrismaPageHeader} from '../ui/PrismaPage';
import {PrismaCard} from '../ui/PrismaCard';
import {useLoadingFeedback} from '../ui/PrismaLoadingFeedback';
import {useViewState,useUnsavedChanges,usePrismaScreenState} from '../ui/PrismaNavigation';
import './processAssessment.css';

export function ProcessAssessmentPage({activeMembership,vacancyId,processId,initialPersonId,onNavigate}:{activeMembership:OrganizationMembership;vacancyId:string;processId?:string;initialPersonId?:string;onNavigate:(path:string)=>void}) {
 const org=activeMembership.organizationId,base=`/vacancies/${vacancyId}/follow-up`,route=processId?`${base}/processes/${processId}/assessment`:`${base}/assessment`;
 const [workspace,setWorkspace]=useState<ProcessAssessmentWorkspace|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null);
 const [step,setStep,replaceStep]=usePrismaScreenState(0),[quantity,setQuantity]=useState(20),[level,setLevel]=useState(2),[duration,setDuration]=useState(60),[mode,setMode]=useState<'bank'|'ai'|'mixed'>('bank'),[requirements,setRequirements]=useState<string[]>([]),[personalize,setPersonalize]=useState(false);
 const [selected,setSelected]=useViewState<string[]>('candidateSelection',initialPersonId?[initialPersonId]:[],route);
 const [emails,setEmails]=useState<Record<string,string>>({}),[expires,setExpires]=useState(''),[subject,setSubject]=useState('Convite para avaliação · Prisma'),[message,setMessage]=useState('Você foi convidado(a) para uma avaliação relacionada à Posição. Acesse seu link pessoal, confira as instruções e responda dentro do prazo.');
 const [deficitOpen,setDeficitOpen]=useState(false),[edit,setEdit]=useState<AssessmentQuestion|null>(null),[resultPerson,setResultPerson]=useState<string|null>(null),[legacy,setLegacy]=useState<{assessment:PositionAssessment;attempt:AssessmentAttempt|null}|null>(null),[reuse,setReuse]=useState<string|null>(null);
 const generation=useRef(0),operationScope=useRef(0),lock=useRef(false),batch=useRef<{fingerprint:string;id:string}|null>(null),generationRequest=useRef<{scope:string;id:string}|null>(null),configDirty=useRef(false),configInitialized=useRef(false);
 const a=workspace?.assessment??null,readOnly=!!workspace&&(!workspace.process.isCurrent||workspace.process.status==='closed');
 const frozen=a?.status==='issued'||a?.status==='cancelled';
 useLoadingFeedback({'Carregando avaliação do processo…':loading,'Montando, salvando ou enviando avaliação…':busy});useUnsavedChanges(!!edit);
 function assertScope(){if(operationScope.current!==generation.current)throw Error('O contexto mudou. Consulte o estado confirmado do processo.');}
 function adopt(next:PositionAssessment){assertScope();setWorkspace(w=>w?{...w,assessment:next}:w);return next;}
 async function load(initialize=false){const scope=generation.current;setLoading(true);try{const w=await service.load(org,vacancyId,processId);if(scope!==generation.current)return w;setWorkspace(w);if(initialize||!configInitialized.current){const x=w.assessment;setQuantity(x?.config.quantity??20);setLevel(x?.config.level??2);setDuration(x?.config.durationMinutes??60);setMode(x?.config.mode??'bank');setRequirements((x?.requirements??w.requirements).map(r=>r.id));setEmails(Object.fromEntries(w.candidates.map(c=>[c.personId,c.email??''])));configInitialized.current=true;if(x?.questions.length)replaceStep(1,true);}return w;}catch(e){if(scope===generation.current)setError(e instanceof Error?e.message:'Falha ao carregar.');throw e;}finally{if(scope===generation.current)setLoading(false);}}
 useEffect(()=>{generation.current++;configInitialized.current=false;configDirty.current=false;batch.current=null;generationRequest.current=null;setWorkspace(null);setError(null);setSelected(initialPersonId?[initialPersonId]:selected);void load(true).catch(()=>{});return()=>{generation.current++;};},[org,vacancyId,processId]);
 async function run(action:()=>Promise<void>){if(lock.current)return;const scope=generation.current;operationScope.current=scope;lock.current=true;setBusy(true);setError(null);setNotice(null);try{await action();}catch(e){if(scope===generation.current)setError(e instanceof Error?e.message:'Operação não concluída.');}finally{lock.current=false;setBusy(false);}}
 const snapshot=(()=>{try{return createDistributionSnapshot(quantity,level);}catch{return null;}})();
 const composition=a?inspectComposition(a.config.distribution,a.requirements.map(r=>r.id),a.questions,a.config.mode,org):null;
 const parts=a?processAssessmentDeficit(a.config.distribution,a.requirements,a.questions):[],missing=parts.reduce((n,p)=>n+p.quantity,0),chunks=splitGenerationParts(parts);
 const complete=!!a&&!!composition&&composition.totalDeficit===0&&composition.uncoveredRequirementIds.length===0&&composition.violations.length===0;
 const candidates=workspace?.candidates??[],eligible=candidates.filter(c=>c.active&&c.stage!=='closed'&&!workspace?.attempts.some(t=>t.personId===c.personId));
 const recipients=eligible.filter(c=>selected.includes(c.personId)).map(c=>({personId:c.personId,email:emails[c.personId]??c.email??''}));
 function changed(){configDirty.current=true;}
 async function mount(){
  if(!snapshot||!requirements.length||requirements.length>quantity)throw Error('Selecione requisitos e uma quantidade múltipla de 10, com pelo menos uma questão por requisito.');
  let current=a;
  if(!current||configDirty.current)current=adopt(await service.mutate(org,vacancyId,'configure',current,{processId:workspace?.process.id,config:{quantity,level,durationMinutes:duration,mode},requirementIds:requirements}));
  configDirty.current=false;
  if(current.generationPending)throw Error('Há um pedido de IA pendente. Atualize para consultar o estado.');
  if(current.config.mode!=='ai'){const bank=await service.bank(org,current.id);assertScope();const questions=assembleProcessAssessment(bank,current.requirements,current.config.distribution,org,current.questions);if(questions.length!==current.questions.length)current=adopt(await service.mutate(org,vacancyId,'questions',current,{questions}));}
  assertScope();
  setStep(1);if(processAssessmentDeficit(current.config.distribution,current.requirements,current.questions).length)setDeficitOpen(true);
 }
 async function generate(){
  if(!a)return;let current=a;setDeficitOpen(false);if(current.config.mode==='bank')current=adopt(await service.mutate(org,vacancyId,'allow_ai',current));
  const requests=splitGenerationParts(processAssessmentDeficit(current.config.distribution,current.requirements,current.questions));
  for(const distribution of requests){
   const requestScope=JSON.stringify([current.id,current.revision,distribution]);if(generationRequest.current?.scope!==requestScope)generationRequest.current={scope:requestScope,id:crypto.randomUUID()};
   const result=await service.generate({organizationId:org,assessmentId:current.id,requestId:generationRequest.current.id,distribution});
   assertScope();const w=await load();assertScope();if(!w?.assessment)throw Error('Não foi possível confirmar o rascunho.');current=w.assessment;
   if(result.status!=='succeeded'){if(result.status==='failed')generationRequest.current=null;throw Error(result.status==='failed'?'A IA não concluiu este pedido. O conteúdo já confirmado foi preservado. Você pode confirmar uma nova tentativa para o déficit.':'Pedido em processamento ou sem confirmação. Atualize os dados antes de tentar novamente.');}
   generationRequest.current=null;
  }
  setNotice('Propostas de IA incorporadas. Revise antes de aprovar e enviar.');
 }
 async function substitute(q:AssessmentQuestion){if(!a)return;const bank=await service.bank(org,a.id);assertScope();const next=bank.find(x=>x.requirementId===q.requirementId&&x.difficulty===q.difficulty&&!a.questions.some(y=>y.id===x.id));if(!next)throw Error('Não há outra questão aprovada e compatível no banco. Edite esta questão ou reconfigure o rascunho.');adopt(await service.mutate(org,vacancyId,'questions',a,{questions:a.questions.map(x=>x.id===q.id?next:x)}));}
 async function send(){if(!a||!recipients.length||!expires)return;const body={organizationId:org,vacancyId,assessmentId:a.id,revision:a.revision,recipients,subject,message,expiresAt:new Date(expires).toISOString()};const fingerprint=JSON.stringify({...body,revision:undefined});if(batch.current?.fingerprint!==fingerprint)batch.current={fingerprint,id:crypto.randomUUID()};const result=await service.send({...body,requestId:batch.current.id});await load();assertScope();setSelected([]);setNotice(`${result.receipts.length} convite(s) registrado(s). Acompanhe o estado de envio de cada Pessoa.`);batch.current=null;}
 if((workspace&&workspace.organizationId!==org)||(loading&&!workspace))return <PrismaPage><Skeleton active /></PrismaPage>;
 if(!workspace)return <PrismaPage><Alert type="error" title={error??'Processo indisponível.'} action={<Space wrap><Button onClick={()=>void load(true).catch(()=>{})}>Tentar novamente</Button><Button onClick={()=>onNavigate(base)}>Ir ao acompanhamento</Button></Space>} /></PrismaPage>;
 return <PrismaPage className="process-assessment"><PrismaPageHeader title="Avaliação do processo" description={`${workspace.positionTitle} · ${workspace.process.name.replace(/^Avaliação /,'Acompanhamento ')}`} extras={<Space wrap><Tag color="blue">Avaliação opcional · decisão humana</Tag>{a?<Tag>{states[a.status]}</Tag>:null}</Space>} actions={<Space wrap><Button type="link" onClick={()=>onNavigate(processId?`${base}/processes/${processId}`:base)}>Ir ao acompanhamento</Button><Button icon={<ReloadOutlined aria-hidden="true" />} loading={loading} disabled={busy} onClick={()=>void load().catch(()=>{})}>Atualizar</Button></Space>} />
 {error?<Alert type="error" showIcon title={error} action={<Button loading={loading} disabled={busy} onClick={()=>void load().catch(()=>{})}>Atualizar dados</Button>} />:null}{notice?<Alert type="info" showIcon title={notice} />:null}{readOnly?<Alert type="info" title="Processo histórico ou encerrado. A prova e os resultados estão preservados para consulta." />:null}
 {frozen?<Alert type="info" title="Prova fixada no primeiro envio" description="Todos os candidatos deste processo recebem estas mesmas questões, versão e duração. Novos candidatos podem receber a mesma prova. Para outra prova, encerre este processo e inicie um novo." />:null}
 {!frozen&&!readOnly&&step===0?<div className="process-assessment-preparation" aria-label="Preparar avaliação"><section className="process-assessment-section" aria-labelledby="assessment-configuration-heading"><div className="process-assessment-section-heading"><span className="process-assessment-section-number" aria-hidden="true">1</span><div><h2 id="assessment-configuration-heading">Configuração</h2><p>Defina os parâmetros da avaliação para este processo.</p></div></div><div className="process-assessment-section-body"><div className="process-assessment-fields">
 <label>Quantidade de questões<InputNumber aria-label="Quantidade de questões" min={10} step={10} value={quantity} onChange={n=>{setQuantity(n??20);changed();}} /></label>
 <label>Nível<Select aria-label="Nível" value={level} onChange={n=>{setLevel(n);changed();}} options={[{value:1,label:'Muito fácil'},{value:2,label:'Fácil'},{value:3,label:'Moderado'},{value:4,label:'Difícil'},{value:5,label:'Muito difícil'}]} /></label>
 <label>Fonte<Select aria-label="Fonte" value={mode} onChange={n=>{setMode(n);changed();}} options={[{value:'bank',label:'Banco'},{value:'ai',label:'IA'},{value:'mixed',label:'Banco + IA'}]} /></label>
 <label>Duração em minutos<InputNumber aria-label="Duração em minutos" min={1} max={240} value={duration} onChange={n=>{setDuration(n??60);changed();}} /></label></div>
 <div className="process-assessment-composition" role="status"><InfoCircleOutlined aria-hidden="true" />{snapshot?<><strong>{snapshot.counts.easy} fáceis · {snapshot.counts.medium} médias · {snapshot.counts.hard} difíceis</strong><span>Cinco alternativas e uma resposta correta por questão.</span></>:<span>Informe uma quantidade múltipla de 10.</span>}</div>
 </div></section><section className="process-assessment-section" aria-labelledby="assessment-requirements-heading"><div className="process-assessment-section-heading"><span className="process-assessment-section-number" aria-hidden="true">2</span><div><h2 id="assessment-requirements-heading">Requisitos da Posição</h2><p>Selecione os requisitos que serão contemplados na avaliação.</p></div></div><div className="process-assessment-section-body"><div className="process-assessment-requirements-header"><p>{requirements.length} requisitos selecionados</p><Button type="link" icon={<SettingOutlined aria-hidden="true" />} aria-expanded={personalize} aria-controls="assessment-requirements" disabled={busy} onClick={()=>setPersonalize(!personalize)}>Personalizar requisitos</Button></div><div id="assessment-requirements" className="process-assessment-requirements">{personalize?<Checkbox.Group disabled={busy} value={requirements} onChange={v=>{setRequirements(v as string[]);changed();}} options={workspace.requirements.map(r=>({value:r.id,label:r.label}))} />:<div className="process-assessment-selected-requirements">{workspace.requirements.filter(r=>requirements.includes(r.id)).map(r=><span className="process-assessment-requirement-chip" key={r.id}><CheckSquareFilled aria-hidden="true" /><span>{r.label}</span></span>)}</div>}</div></div></section>
 {requirements.length>quantity?<Alert type="warning" title="Há mais requisitos que questões. Aumente a quantidade ou personalize os requisitos para garantir cobertura." />:null}<div className="process-assessment-mount"><Button type="primary" loading={busy} disabled={!snapshot||!requirements.length||requirements.length>quantity||!!a?.generationPending} onClick={()=>{if(a?.questions.length&&configDirty.current)Modal.confirm({title:'Reconfigurar o rascunho?',content:'A composição atual será substituída. A prova ainda não foi enviada.',okText:'Reconfigurar',onOk:()=>run(mount)});else void run(mount);}}>Montar avaliação</Button></div>
 {!a&&workspace.reusable.length?<><p>Ou reutilize uma prova compatível de um processo anterior:</p><Space className="process-assessment-reuse" wrap><Select aria-label="Prova anterior compatível" placeholder="Selecione uma prova anterior" value={reuse} onChange={setReuse} options={workspace.reusable.map(x=>({value:x.id,label:`${x.processName} · ${x.quantity} questões · ${x.durationMinutes} min`}))} /><Button disabled={!reuse} loading={busy} onClick={()=>void run(async()=>{if(reuse){adopt(await service.reuse(org,vacancyId,workspace.process.id,reuse));setStep(1);}})}>Reutilizar prova</Button></Space></>:null}
 </div>:null}
 {a&&(step===1||frozen||readOnly)?<PrismaCard title="Revisar avaliação"><p>{a.questions.length} de {a.config.quantity} questões · {a.config.durationMinutes} minutos · nível {a.config.level} · versão da Posição preservada</p>
 {!frozen&&!readOnly?<Space wrap><Button disabled={busy} onClick={()=>setStep(0)}>Editar configuração</Button>{missing?<Button loading={busy} disabled={!!a.generationPending} onClick={()=>setDeficitOpen(true)}>Completar {missing} questões por IA</Button>:null}</Space>:null}
 {a.generationPending?<Alert type="info" title="Pedido de IA em processamento ou sem confirmação. Atualize para consultar o estado; nenhum novo pedido é iniciado automaticamente." />:null}
 {!a.questions.length?<Empty description="Nenhuma questão montada." />:<Collapse items={a.questions.map((q,i)=>({key:q.id,label:<span>Questão {i+1} · {q.stem} <Tag color={q.review==='pending'?'orange':'green'}>{q.review==='pending'?'Nova ou alterada · revisar':'Aprovação preservada'}</Tag></span>,children:<><p>{a.requirements.find(r=>r.id===q.requirementId)?.label} · {({easy:'Fácil',medium:'Média',hard:'Difícil'})[q.difficulty]}</p>{q.options.map(o=><p key={o.id}><strong>{o.id}</strong> · {o.label}{o.id===q.correctOptionId?' · Correta':''}</p>)}<p>{q.explanation}</p><p>Origem: {q.source==='bank'?'Banco':'IA'} · versão {q.version} · método {q.provenance.method} · autor {q.approvedBy??q.provenance.authorId??'aguardando revisão'}</p>{!frozen&&!readOnly?<Space><Button disabled={busy} onClick={()=>setEdit(structuredClone(q))}>Editar questão</Button><Button loading={busy} onClick={()=>void run(()=>substitute(q))}>Substituir pelo banco</Button></Space>:null}</>}))} />}
 {!readOnly?<><h3>Candidatos e convites</h3><p>Selecione as Pessoas para esta mesma prova. O e-mail editado vale apenas para o convite.</p>
 <Table rowKey="personId" pagination={false} scroll={{x:480}} dataSource={candidates} rowSelection={{selectedRowKeys:selected,onChange:keys=>setSelected(keys as string[]),getCheckboxProps:c=>({disabled:busy||!eligible.some(x=>x.personId===c.personId)})}} columns={[{title:'Pessoa',dataIndex:'name'},{title:'E-mail do convite',render:(_,c)=><Input aria-label={`E-mail de ${c.name}`} type="email" value={emails[c.personId]??c.email??''} disabled={busy||!eligible.some(x=>x.personId===c.personId)} onChange={e=>setEmails({...emails,[c.personId]:e.target.value})} />},{title:'Aplicação',render:(_,c)=>{const t=workspace.attempts.find(t=>t.personId===c.personId);return t?<Tag>{states[t.status]}</Tag>:<span>{c.stage==='closed'?'Acompanhamento encerrado':'Não enviada'}</span>;}}]} />
 <label>Prazo de acesso<Input aria-label="Prazo de acesso" type="datetime-local" value={expires} disabled={busy} onChange={e=>setExpires(e.target.value)} /></label><p>A duração da prova começa no início; o prazo de acesso é a data limite do convite.</p>
 <Collapse items={[{key:'invite',label:'Personalizar assunto e mensagem',children:<><label>Assunto<Input value={subject} disabled={busy} onChange={e=>setSubject(e.target.value)} /></label><label>Mensagem<Input.TextArea rows={3} value={message} disabled={busy} onChange={e=>setMessage(e.target.value)} /></label></>}]} />
 <Button aria-label={frozen?`Enviar a mesma prova aos ${recipients.length} candidatos`:`Aprovar e enviar aos ${recipients.length} candidatos`} type="primary" loading={busy} disabled={!complete||!recipients.length||recipients.some(c=>!c.email)||!expires||!!a.generationPending} onClick={()=>void run(send)}>{frozen?`Enviar a mesma prova aos ${recipients.length} candidatos`:`Aprovar e enviar aos ${recipients.length} candidatos`}</Button></>:null}
 </PrismaCard>:null}
 {workspace.attempts.length?<PrismaCard title="Aplicações e resultados individuais"><Table rowKey="id" pagination={false} scroll={{x:480}} dataSource={workspace.attempts} columns={[{title:'Pessoa',render:(_,t)=>candidates.find(c=>c.personId===t.personId)?.name??'Pessoa'},{title:'Estado',render:(_,t)=><><Tag>{states[t.status]}</Tag>{t.deliveries.map(d=><div key={d.id}><Tag>{states[d.state]}</Tag>{d.providerEmailId?<small>Aceitação pelo provedor; entrega e abertura não verificadas.</small>:null}{['failed','queued','sending'].includes(d.state)&&!readOnly?<Button disabled={busy} onClick={()=>void run(async()=>{await service.dispatch({organizationId:org,vacancyId,processId:workspace.process.id,deliveryId:d.id});await load();})}>Retomar envio</Button>:null}</div>)}</>},{title:'Resultado',render:(_,t)=><Space wrap><Button onClick={()=>setResultPerson(t.personId)}>Ver resultado e atividade</Button>{!readOnly&&!['submitted','cancelled'].includes(t.status)?<Button disabled={busy} onClick={()=>Modal.confirm({title:'Cancelar esta aplicação?',content:'O link desta Pessoa será revogado. A prova e o histórico serão preservados.',okText:'Cancelar aplicação',onOk:()=>run(async()=>{await service.cancel(org,t.id);await load();})})}>Cancelar aplicação</Button>:null}</Space>}]} /></PrismaCard>:null}
 {workspace.legacy.length?<Collapse className="process-assessment-history" defaultActiveKey={window.matchMedia('(min-width: 769px)').matches?['legacy']:[]} items={[{key:'legacy',label:<div className="process-assessment-history-heading"><HistoryOutlined aria-hidden="true" /><div><h2>Avaliações individuais anteriores</h2><p>Histórico preservado. As novas avaliações pertencem ao processo.</p></div></div>,children:workspace.legacy.map(x=><div className="process-assessment-history-row" key={x.id}><span>{candidates.find(c=>c.personId===x.personId)?.name??'Pessoa'} · {states[x.status]}</span><Button type="link" aria-label={`Consultar · ${candidates.find(c=>c.personId===x.personId)?.name??'Pessoa'} · ${states[x.status]}`} disabled={busy} onClick={()=>void run(async()=>{const w=await positionAssessmentService.load(org,vacancyId,x.personId),assessment=w.assessments.find(a=>a.id===x.id);assertScope();if(assessment)setLegacy({assessment,attempt:w.attempts.find(t=>t.assessmentId===x.id)??null});})}>Consultar</Button></div>)}]} />:null}
 <Modal open={deficitOpen} title={a?.config.mode==='ai'?'Gerar questões por IA?':'Não há questões suficientes no banco'} onCancel={()=>setDeficitOpen(false)} footer={<Space><Button onClick={()=>setDeficitOpen(false)}>Cancelar</Button><Button type="primary" loading={busy} disabled={!missing||!!a?.generationPending} onClick={()=>void run(generate)}>Gerar {missing} questões por IA</Button></Space>}><p>{a?.questions.length??0} questões montadas · faltam {missing}. A IA completará somente o déficit e as propostas ficarão pendentes de revisão.</p><p>{chunks.length} pedido(s), até 20 questões e US$ 0,25 por pedido. Limite máximo autorizado nesta confirmação: US$ {(chunks.length*0.25).toFixed(2)}. Limite por empresa: US$ 10/mês.</p></Modal>
 <Modal open={!!edit} title="Editar questão · nova revisão necessária" onCancel={()=>setEdit(null)} okText="Salvar para revisão" confirmLoading={busy} onOk={()=>void run(async()=>{if(!a||!edit)return;adopt(await service.mutate(org,vacancyId,'questions',a,{questions:a.questions.map(q=>q.id===edit.id?edit:q)}));setEdit(null);})}><Input.TextArea aria-label="Enunciado" value={edit?.stem} onChange={e=>setEdit(q=>q?{...q,stem:e.target.value}:q)} />{edit?.options.map((o,i)=><div className="process-assessment-option" key={o.id}><Radio checked={edit.correctOptionId===o.id} aria-label={`Marcar ${o.id} como correta`} onChange={()=>setEdit({...edit,correctOptionId:o.id})} /><Input aria-label={`Alternativa ${o.id}`} value={o.label} onChange={e=>setEdit(q=>q?{...q,options:q.options.map((p,n)=>i===n?{...p,label:e.target.value}:p)}:q)} /></div>)}<Input.TextArea aria-label="Justificativa" value={edit?.explanation} onChange={e=>setEdit(q=>q?{...q,explanation:e.target.value}:q)} /></Modal>
 <Modal open={!!resultPerson} title={candidates.find(c=>c.personId===resultPerson)?.name??'Resultado individual'} onCancel={()=>setResultPerson(null)} footer={null} width={850}>{a?<AssessmentAttemptResults assessment={a} attempt={workspace.attempts.find(t=>t.personId===resultPerson)??null} />:null}</Modal>
 <Modal open={!!legacy} title="Histórico individual · somente consulta" onCancel={()=>setLegacy(null)} footer={null} width={850}>{legacy?<><p>{legacy.assessment.config.quantity} questões · {legacy.assessment.config.durationMinutes} minutos</p>{legacy.attempt?<AssessmentAttemptResults assessment={legacy.assessment} attempt={legacy.attempt} />:<Collapse items={legacy.assessment.questions.map(q=>({key:q.id,label:q.stem,children:<>{q.options.map(o=><p key={o.id}>{o.id} · {o.label}</p>)}<p>Correta: {q.correctOptionId} · {q.explanation}</p></>}))} />}</>:null}</Modal>
 </PrismaPage>;
}
