import {createRoot} from 'react-dom/client';import {useState} from 'react';import {ConfigProvider} from 'antd';import ptBR from 'antd/locale/pt_BR';import {TeamOutlined} from '@ant-design/icons';
import {ProcessAssessmentPage} from '../../../web/src/pages/ProcessAssessmentPage';import {PositionFollowUpPage} from '../../../web/src/pages/PositionFollowUpPage';import {processAssessmentService as service} from '../../../web/src/infrastructure/supabase/processAssessmentService';import {positionFollowUpService} from '../../../web/src/infrastructure/supabase/positionFollowUpService';import {vacancyService} from '../../../web/src/infrastructure/supabase/vacancyService';
import {PrismaAppShell} from '../../../web/src/ui/PrismaAppShell';import {PrismaViewStateProvider} from '../../../web/src/ui/PrismaNavigation';import {PrismaLoadingFeedback} from '../../../web/src/ui/PrismaLoadingFeedback';import {prismaTheme} from '../../../web/src/ui/theme';import {createDistributionSnapshot} from '../../../src/domain/positionAssessment';import type {AssessmentQuestion,PositionAssessment} from '../../../web/src/domain/positionAssessmentData';import type {ProcessAssessmentWorkspace} from '../../../web/src/domain/processAssessmentData';import {vacancy,fixture as followUp,uuid} from '../position-follow-up/fixture';
import 'antd/dist/reset.css';import '../../../web/src/styles.css';import '../../../web/src/ui/foundation.css';
import {positionAssessmentService} from '../../../web/src/infrastructure/supabase/positionAssessmentService';
const state=new URLSearchParams(location.search).get('state')??'bank';const reqs=state==='visual'?['Desenvolvimento de APIs REST','Node.js','SAP','Kubernetes','Azure','RabbitMQ','Docker','Java','Segurança de aplicações','Kafka','AWS','Python','Abap'].map((label,n)=>({id:uuid(60+n),label,competencyKey:`visual-${n}`})):[{id:uuid(60),label:'APIs REST',competencyKey:'api'},{id:uuid(61),label:'SQL',competencyKey:'sql'}];
const questions:AssessmentQuestion[]=Array.from({length:20},(_,n)=>({organizationId:uuid(3),id:uuid(100+n),version:'qa-bank-1',requirementId:reqs[n%2]!.id,competencyKey:reqs[n%2]!.competencyKey,difficulty:n<8?'easy':n<16?'medium':'hard',language:'pt-BR',stem:`Questão sintética ${n+1}: qual alternativa representa a solução?`,options:['A','B','C','D','E'].map(id=>({id,label:`Alternativa ${id}`})),correctOptionId:'A',explanation:'Justificativa sintética para o teste da interface.',source:'bank',review:'approved',approvedBy:uuid(6),approvedAt:'2026-10-10T12:00:00Z',provenance:{method:'approved-item-bank',version:'qa-bank-1',authorId:uuid(6)}}));
const template:PositionAssessment={id:uuid(70),organization_id:uuid(3),person_id:null,process_id:uuid(5),vacancy_id:uuid(1),position_version_id:uuid(2),revision:1,status:state==='issued'?'issued':'draft',requirements:reqs,config:{quantity:20,level:2,durationMinutes:60,mode:'bank',distribution:createDistributionSnapshot(20,2)},questions:state==='issued'?questions:[],created_at:'2026-10-10T12:00:00Z'};
followUp.data.process={id:uuid(5),name:'Acompanhamento 01',status:state==='history'?'closed':'active',revision:1,isCurrent:state!=='history',sequence:1};followUp.data.processes=[{...followUp.data.process,isCurrent:true,sequence:1}];
const workspace:ProcessAssessmentWorkspace={contract:'process-assessment-1.0.0',organizationId:uuid(3),vacancyId:uuid(1),positionVersionId:uuid(2),positionTitle:vacancy.title,process:{id:uuid(5),name:'Acompanhamento 01',status:state==='history'?'closed':'active',revision:1,isCurrent:state!=='history'},requirements:reqs,assessment:['issued','history'].includes(state)?template:null,candidates:followUp.data.entries.map((e,n)=>({personId:e.personId,name:e.fullName,email:`candidato${n}@example.invalid`,stage:e.stage,active:true})),attempts:[],reusable:state==='reuse'?[{id:uuid(71),processName:'Acompanhamento anterior',quantity:20,durationMinutes:60}]:[],legacy:[]};
if(state==='issued')workspace.attempts=[{id:uuid(80),personId:uuid(10),assessmentId:uuid(70),status:'submitted',expiresAt:'2026-12-10T12:00:00Z',submittedAt:'2026-10-10T12:55:00Z',answers:Object.fromEntries(questions.map(q=>[q.id,'A'])),result:{correct:20,total:20,requirements:reqs.map(r=>({id:r.id,label:r.label,correct:10,total:10}))},deliveries:[{id:uuid(81),state:'sent',recipient:'candidato0@example.invalid',subject:'Convite',message:'Instruções',providerEmailId:uuid(82),errorCategory:null}],events:[{id:1,question_id:uuid(100),question_version:'qa-bank-1',kind:'focus_episode',sequence:1,client_at_ms:Date.parse('2026-10-10T12:05:00Z'),received_at:'2026-10-10T12:05:20Z',method:'position-assessment-focus-1.0.0',payload:{durationMs:18000}}]}];
const fixture={calls:[] as Array<{action:string;body:any}>,fail:false,hold:false,workspace,path:'/follow-up',questions};Object.assign(window,{__processFixture:fixture});
if(state==='visual'){workspace.positionTitle='Desenvolvedor backend';workspace.candidates[0]!.name='Pessoa exemplo';workspace.legacy=[{id:uuid(90),personId:workspace.candidates[0]!.personId,status:'draft',createdAt:'2026-10-10T12:00:00Z'}];}
positionAssessmentService.load=async()=>{fixture.calls.push({action:'legacy_load',body:null});return {assessments:[{...structuredClone(template),id:uuid(90),person_id:workspace.candidates[0]!.personId}],attempts:[]} as any;};
const gate=async()=>{while(fixture.hold)await new Promise(r=>setTimeout(r,25));await new Promise(r=>setTimeout(r,80));if(fixture.fail)throw Error('Falha sintética. O último estado confirmado foi preservado.');};
vacancyService.load=async()=>vacancy;positionFollowUpService.load=async()=>structuredClone(followUp.data);
service.load=async()=>{fixture.calls.push({action:'load',body:null});await gate();return structuredClone(workspace);};
service.bank=async()=>{fixture.calls.push({action:'bank',body:null});await gate();return structuredClone(state==='partial'?questions.slice(0,10):state==='empty'?[]:questions);};
service.mutate=async(_o,_v,action,a,payload:any={})=>{fixture.calls.push({action,body:payload});await gate();const current=workspace.assessment??structuredClone(template);workspace.assessment=current;
 if(action==='configure'){current.config={...payload.config,distribution:createDistributionSnapshot(payload.config.quantity,payload.config.level)};current.requirements=reqs.filter(r=>payload.requirementIds.includes(r.id));current.questions=[];}
 if(action==='questions')current.questions=structuredClone(payload.questions).map((q:AssessmentQuestion)=>({...q,review:q.stem.startsWith('Editada')?'pending':q.review}));
 if(action==='allow_ai')current.config.mode='mixed';current.revision++;return structuredClone(current);};
service.generate=async(body:any)=>{fixture.calls.push({action:'generate',body});await gate();const current=workspace.assessment!;for(const part of body.distribution)for(let n=0;n<part.quantity;n++)current.questions.push({...questions[0]!,id:crypto.randomUUID(),requirementId:part.requirementId,competencyKey:reqs.find(r=>r.id===part.requirementId)!.competencyKey,difficulty:part.difficulty,source:'ai',review:'pending',approvedBy:undefined,approvedAt:undefined,provenance:{method:'qa-ai',version:'qa-ai-1',authorId:null}} as AssessmentQuestion);current.revision++;return {status:'succeeded'};};
service.send=async(body:any)=>{fixture.calls.push({action:'send_batch',body});await gate();workspace.assessment!.status='issued';workspace.assessment!.revision++;const receipts=body.recipients.map((r:any,n:number)=>({personId:r.personId,deliveryId:uuid(200+n),state:'queued'}));workspace.attempts.push(...body.recipients.map((r:any,n:number)=>({id:uuid(300+n),personId:r.personId,assessmentId:template.id,status:'invited',expiresAt:body.expiresAt,submittedAt:null,answers:{},result:null,deliveries:[{id:uuid(200+n),state:'queued',recipient:r.email,subject:body.subject,message:body.message,providerEmailId:null,errorCategory:null}],events:[]})));return {status:'queued',receipts};};
service.reuse=async()=>{fixture.calls.push({action:'reuse',body:null});await gate();workspace.assessment={...structuredClone(template),questions};return structuredClone(workspace.assessment);};
const membership={organizationId:uuid(3),organizationName:'Empresa sintética',role:'recruiter',groupId:null,groupName:null}as const;
function App(){const [path,setPath]=useState(state==='follow-up'?`/vacancies/${uuid(1)}/follow-up`:`/vacancies/${uuid(1)}/follow-up/assessment`);function navigate(p:string){fixture.path=p;setPath(p);}return <ConfigProvider locale={ptBR} theme={prismaTheme}><PrismaViewStateProvider scope="process-fixture"><PrismaLoadingFeedback/><PrismaAppShell activeMembership={membership} memberships={[membership]} profileName="Bruno" profileSubtitle="Recrutador" navigationItems={[{path:'/vacancies',label:'Posições',icon:<TeamOutlined/>}]} selectedPath="/vacancies" onNavigate={navigate} onOrganizationChange={()=>{}} onSignOut={()=>{}}>{path.endsWith('/assessment')?<ProcessAssessmentPage activeMembership={membership} vacancyId={uuid(1)} onNavigate={navigate}/>:<PositionFollowUpPage activeMembership={membership} vacancyId={uuid(1)} onNavigate={navigate}/>}</PrismaAppShell></PrismaViewStateProvider></ConfigProvider>;}
createRoot(document.getElementById('root')!).render(<App/>);
