import {Alert,Empty,Table,Tag,Tabs} from 'antd';
import {useState} from 'react';
import type {AssessmentAttempt,AssessmentQuestion,PositionAssessment} from '../domain/positionAssessmentData';
export const assessmentStateLabels:Record<string,string>={draft:'Rascunho',ready:'Revisado',issued:'Prova fixada',cancelled:'Cancelado',invited:'Aguardando início',started:'Em andamento',submitted:'Concluído',queued:'Na fila',sending:'Enviando',sent:'Aceito pelo provedor',failed:'Falhou',reconciliation_required:'Requer conciliação'};
export function AssessmentAttemptResults({assessment,attempt}:{assessment:PositionAssessment;attempt:AssessmentAttempt|null}) {
 const [tab,setTab]=useState('summary');if(!attempt)return <Empty description="Nenhuma aplicação emitida." />;
 return <><Tag>{assessmentStateLabels[attempt.status]??attempt.status}</Tag><Tabs activeKey={tab} onChange={setTab} items={[{key:'summary',label:'Resumo'},{key:'answers',label:'Questões e respostas'},{key:'activity',label:'Atividade por questão'}]} />
 {tab==='summary'?<><p>{attempt.result?`${attempt.result.correct} / ${attempt.result.total} respostas corretas`:'Resultado disponível após a submissão completa.'}</p><p>Resultado separado do Prisma Score.</p>{attempt.result?.requirements.map(r=><p key={r.id}>{r.label}: {r.correct} / {r.total}</p>)}<p>Prazo: {new Date(attempt.expiresAt).toLocaleString('pt-BR')}</p>{attempt.submittedAt?<p>Concluída em {new Date(attempt.submittedAt).toLocaleString('pt-BR')}</p>:null}</>:null}
 {tab==='answers'?<Table rowKey="id" scroll={{x:500}} pagination={{pageSize:5,showSizeChanger:false}} dataSource={assessment.questions} columns={[{title:'Questão',render:(_,q:AssessmentQuestion)=><details><summary>{q.stem}</summary>{q.options.map(o=><p key={o.id}>{o.id} · {o.label}</p>)}<p>{q.explanation}</p><p>{q.source==='bank'?'Banco':'IA'} · versão {q.version} · método {q.provenance.method}</p></details>},{title:'Resposta',render:(_,q:AssessmentQuestion)=>attempt.answers[q.id]??'Sem resposta'},{title:'Correta',dataIndex:'correctOptionId'}]} />:null}
 {tab==='activity'?<><Table rowKey="id" scroll={{x:600}} pagination={{pageSize:5,showSizeChanger:false}} dataSource={assessment.questions} columns={[
 {title:'Questão',render:(_,q:AssessmentQuestion)=>assessment.questions.indexOf(q)+1},
 {title:'Foco',render:(_,q:AssessmentQuestion)=>{const rows=attempt.events.filter(e=>e.question_id===q.id&&e.kind==='focus_episode');return rows.length?`${rows.length} episódio(s) · ${Math.round(rows.reduce((n,e)=>n+Number(e.payload.durationMs??0),0)/1000)}s`:'Não observado';}},
 {title:'Mouse total / maior',render:(_,q:AssessmentQuestion)=>{const rows=attempt.events.filter(e=>e.question_id===q.id&&e.kind==='mouse_idle_before_first_choice'&&e.payload.totalIdleMs!==null);return rows.length?`${Math.round(rows.reduce((n,e)=>n+Number(e.payload.totalIdleMs),0)/1000)}s / ${Math.round(Math.max(...rows.map(e=>Number(e.payload.longestIdleMs)))/1000)}s`:'Indisponível / não aplicável';}},
 {title:'Zoom / atalhos',render:(_,q:AssessmentQuestion)=>`${attempt.events.filter(e=>e.question_id===q.id&&e.kind==='zoom_observed').length} / ${attempt.events.filter(e=>e.question_id===q.id&&e.kind==='capture_shortcut_observed').length}`},
 {title:'Timeline e método',render:(_,q:AssessmentQuestion)=><details><summary>Ver sinais</summary>{attempt.events.filter(e=>e.question_id===q.id).map(e=><p key={e.id}>{new Date(Number(e.client_at_ms)).toLocaleTimeString('pt-BR')} · {e.kind} · {e.method}<br />Recebido: {new Date(e.received_at).toLocaleString('pt-BR')}<br />{Object.entries(e.payload).map(([k,v])=>`${k}: ${v??'indisponível'}`).join(' · ')}</p>)}</details>}]}/><Alert type="info" title="Os sinais são observações parciais. Não comprovam pesquisa, captura de tela ou fraude, não identificam o destino de uma saída de foco e não alteram o Score ou a etapa. A ausência de sinais não comprova ausência de atividade." /></>:null}
 </>;
}
