import { profileFixture, documentFixture, attemptFixture } from "../../fixtures/personFlow.js";
import { m72Fixture, m72DeclaredEvidence } from "../../fixtures/m72PersonEvidence.js";
import type { PersonIngestionWorkspace, ProfileVersionView } from "../../../web/src/domain/personIngestion.js";
import type { ProfileSynthesisView } from "../../../src/domain/profileSynthesis.js";
import type { CompetencyCurationAdapter } from "../../../web/src/domain/profileCompetencyCuration.js";
// @ts-expect-error Shared deterministic source fixture.
import { result, sources } from "../../fixtures/profileSynthesis.mjs";
export const scenario = new URLSearchParams(location.search).get("case") ?? "reference";
export const calls = { workspace: 0, versions: 0, profile: 0, load: 0, request: 0, retry: 0, source: 0, review: 0, navigations: [] as string[] };
export const draft = profileFixture({ identity: {fullName:"Marina Costa"}, contact:{city:"São Paulo",state:"SP",email:null,phone:null,linkedin:null}, professionalTitle:"Gerente de Operações", areasOfExpertise:["Gestão de operações","Logística"], summary:"Resumo original do currículo, preservado integralmente. Experiência em operações, logística e liderança de equipes.", professionalObjective:"Continuar em gestão de operações, com foco em serviços.",
 experiences:[{id:"current",source:"human",evidenceText:"Gestão de operações.",role:"Gerente de Operações",organization:"NovaVia Serviços",period:"Jan/2022 - Atual",description:"Gestão de operações, organização de rotinas, indicadores e melhoria de processos.",page:1},{id:"prior",source:"human",evidenceText:"Gestão de operações.",role:"Coordenadora de Operações",organization:"Grupo Aurora",period:"Jan/2018 - Dez/2021",description:"Gestão de operações nas unidades de atendimento.",page:1},{id:"old",source:"human",evidenceText:"Logística.",role:"Supervisora de Equipe",organization:"Rede Horizonte",period:"Jan/2015 - Dez/2017",description:"Logística e distribuição.",page:1}],
 education:[{id:"mba",source:"human",evidenceText:"MBA em Gestão de Negócios",description:"Formação sintética publicada integralmente.",course:"Gestão de Negócios",institution:"Instituto Horizonte",period:"2019 - 2020",level:"postgraduate",qualification:"mba",status:"completed",classificationOrigin:"human",page:1},{id:"specialization",source:"human",evidenceText:"Especialização em Gestão de Projetos",description:null,course:"Gestão de Projetos",institution:"Instituto Horizonte",period:"2017 - 2018",level:"postgraduate",qualification:"specialization",status:"completed",classificationOrigin:"human",page:1}], languages:["Inglês · avançado"],certifications:["Credencial sintética"],customSections:[{id:"other",name:"Projetos",format:"text",source:"human",items:[{id:"project",value:"Projeto sintético preservado."}]}]
});
const profileSummary = {id:"profile-fixture",profileVersion:3,sourceDocumentId:"doc1",approvedAt:"2026-10-06T12:00:00Z",createdAt:"2026-10-06T12:00:00Z"};
const doc2=documentFixture({id:"doc2",filename:"curriculo_marina_v2.pdf",createdAt:"2026-10-05T12:00:00Z",processedAt:"2026-10-05T12:00:00Z"});
const doc1=documentFixture({id:"doc1",filename:"curriculo_marina_v1.pdf",documentVersion:1,createdAt:"2026-10-01T12:00:00Z",processedAt:"2026-10-01T12:00:00Z",status:"completed",reviewState:"approved",profileVersion:3});
if(scenario==="document-failure") {doc2.status="processing_failed";doc2.reviewState="not_ready";doc2.latestAttempt=attemptFixture({state:"failed_structuring",failureCode:"invalid_structure"});doc2.reviewAttempt=null;}
export const workspace:PersonIngestionWorkspace={person:{id:"person-fixture",organizationId:"org-fixture",fullName:"Marina Costa",lifecycle:"candidate",operationalStatus:scenario==="archived"?"archived":"active",archivedAt:null,mergedIntoPersonId:null,profileState:"generated",latestSourceType:"resume_pdf",latestSourceAt:doc2.createdAt,updatedAt:"2026-10-06T12:00:00Z",privateData:{fullName:"Marina Costa",email:"private@example.invalid",phoneCountryIso2:"BR",phoneCountryLabel:"Brasil",phoneCountryCode:"55",phoneNationalNumber:"",phoneE164:"",birthDate:null,city:"São Paulo",countryCode:"SP",notes:"Dado privado sintético"},currentProfile:scenario==="no-profile"?null:profileSummary,latestDocument:doc2,documentCount:2,pendingReviewCount:1},documents:scenario==="clean"?[doc1]:[doc2,doc1],selectedDocument:doc2,pages:[],draft:{...draft,education:[{...draft.education[0]!,period:"Atual"}]}};
export const versions:ProfileVersionView[]=scenario==="no-profile"?[]:[{...profileSummary,profileData:draft,reviewStatus:"approved",processingAttemptId:null,approvedByAuthUserId:null,supersededAt:null}];
export const projection=m72Fixture();
projection.associations=Array.from({length:42},(_,i)=>({...structuredClone(m72DeclaredEvidence),id:`association-${i}`,concept:{...m72DeclaredEvidence.concept,id:`concept-${i%18}`,label:i%18===0?"Gestão de operações":`Competência ${i%18+1}`},evidence:{...m72DeclaredEvidence.evidence,id:`evidence-${i}`,title:`Relato publicado ${i+1}`}}));
projection.normalization.items=scenario==="clean"?[]:Array.from({length:3},(_,i)=>({originalIndex:i,originalTerm:`Declaração ${i+1}`,sourceText:`Declaração ${i+1}`,normalizedTerm:`Declaração ${i+1}`,searchTerms:[],state:"unresolved" as const,reason:"Associação pendente"}));
projection.normalization.coverage={totalItemCount:21,associatedItemCount:18,uniqueConceptCount:18,pendingItemCount:projection.normalization.items.length,uniquePendingTermCount:projection.normalization.items.length};
projection.issues=[];
const analysis=structuredClone(result);
const statement=(text:string)=>({text,nature:"published_fact",sourceIds:[sources[2].id]});
analysis.overview=[
 "Marina construiu sua trajetória em operações de serviços e distribuição. Os registros mostram a passagem da supervisão para a coordenação e, depois, para a gestão de operações, com ampliação das responsabilidades sobre equipes, rotinas e acompanhamento de indicadores.",
 "Sua atuação conecta atendimento, organização da execução e melhoria de processos. As experiências publicadas descrevem participação na revisão de fluxos, no planejamento de escalas e na articulação entre a operação e as áreas de apoio.",
 "Essa leitura indica continuidade na área de operações. Os registros ainda não detalham o tamanho das equipes, a autonomia sobre orçamento ou as medidas dos resultados relatados."
].map(statement);
const paragraphs=[
 ["A trajetória mantém continuidade em operações, com passagem por supervisão, coordenação e gestão. Na NovaVia, o registro atual descreve organização da operação e acompanhamento de indicadores.","As mudanças sugerem ampliação de responsabilidades; o relato não permite quantificar o aumento de equipe ou orçamento."],
 ["As atividades incluem revisão de rotinas, planejamento de escalas e coordenação do atendimento. Também aparecem acompanhamento de indicadores e articulação com áreas de apoio.","Os registros descrevem sua participação na execução, mas não separam todas as entregas individuais das realizadas pela equipe."],
 ["Há atuação em serviços e distribuição, com coordenação de equipes e organização de rotinas. Os cargos estão acompanhados de atividades de gestão operacional.","O tamanho das equipes, o orçamento e os limites de decisão não foram detalhados."],
 ["Gestão de operações e melhoria de processos aparecem ligadas à revisão de fluxos e ao acompanhamento de indicadores. A coordenação de equipes está relacionada ao planejamento das rotinas de atendimento.","Esses registros contextualizam o uso declarado; não equivalem a uma verificação prática."],
 ["Foram relatadas iniciativas de organização de escalas e revisão de fluxos de atendimento. Os registros apresentam as entregas realizadas, mas não informam medidas anteriores e posteriores.","Ainda não é possível quantificar efeitos em prazo, produtividade ou qualidade."],
 ["MBA em Gestão de Negócios e especialização em Gestão de Projetos constam como concluídos. Os temas se relacionam às atividades de planejamento e organização descritas.","Não há relato suficiente para atribuir uma entrega específica à aplicação de um desses cursos."],
 ["O objetivo publicado é continuar em gestão de operações, com foco em serviços. A experiência recente apresenta continuidade nessa área.","O Perfil não informa preferência por porte de empresa ou modelo de trabalho."],
 ["Perguntas para aprofundar os registros, sem desqualificar a trajetória."]
];
analysis.answers.forEach((a:{statements:unknown[];missingInformation:string[]},i:number)=>{a.statements=paragraphs[i]!.map(statement);a.missingInformation=[];});
analysis.clarifications=["Qual fluxo de atendimento você redesenhou e qual foi sua participação?","Que indicadores acompanhava antes e depois da mudança?","Qual era o tamanho da equipe e quais decisões dependiam de aprovação?"].map(text=>({text,questionId:"clarifications",sourceIds:[sources[2].id]}));
if(scenario==="long")for(const answer of analysis.answers)answer.statements.push(...Array.from({length:8},(_,i)=>statement(`Trecho integral adicional ${i+1}: ${paragraphs[0]![0]}`)));
export const synthesisView:ProfileSynthesisView={organizationId:"org-fixture",personId:"person-fixture",profileId:"profile-fixture",profileVersion:3,state:scenario==="analysis-failure"?"failed":scenario==="not-requested"?"not_requested":"complete",analysisId:"synthetic",generatedAt:"2026-10-06T12:00:00Z",model:"synthetic",result:scenario==="analysis-failure"||scenario==="not-requested"?null:analysis,previous:null,sources:sources.map(({text,...source}:{text:string})=>source),errorCode:null,basisHash:"a".repeat(64)};
export const adapter={load:async()=>{calls.load++;return structuredClone(synthesisView);},request:async()=>{calls.request++;return structuredClone(synthesisView);},retry:async()=>{calls.retry++;return structuredClone(synthesisView);},source:async(_analysis:string,id:string)=>{calls.source++;if(scenario==="source-failure")throw Error("private diagnostic");return {...sources.find((x:{id:string})=>x.id===id),text:"Trecho da fonte sintética, sem dados reais."};}};
export const curation:CompetencyCurationAdapter={canUseGlobal:false,loadSubgroups:async()=>[],search:async()=>[],suggestDescription:async()=>"",save:async()=>({projection,outcome:"alias"}),refresh:async()=>projection,classify:async()=>projection,loadEvidenceSources:async()=>[],linkEvidence:async()=>projection};
export const ingestion={loadWorkspace:async(_org:string,_person:string,doc?:string)=>{calls.workspace++;if(scenario==="operations-failure")throw Error("private operation");return {...workspace,selectedDocument:workspace.documents.find(x=>x.id===doc)??workspace.selectedDocument};},listProfileVersions:async()=>{calls.versions++;return versions;},startProfileReview:async()=>{calls.review++;return "review-fixture";},startProfileVersionReview:async()=>{calls.review++;return "new-review";}};
export const repository={loadPersonProfile:async()=>{calls.profile++;return {operationalStatus:workspace.person.operationalStatus,person:{id:"person-fixture",organizationId:"org-fixture",fullName:"Marina Costa",lifecycle:"candidate",createdAt:"2026-10-01T12:00:00Z",hasStructuredProfile:scenario!=="no-profile"},profile:scenario==="no-profile"?null:{...draft,...profileSummary,current:true,extractionVersion:"synthetic",inferenceVersion:"synthetic"},evidence:[],inferences:[],competencies:[],normalizedKnowledge:[],professionalEvidence:projection,professionalEvidenceError:null,privateContact:null};}};
